# Level 01: Goal Only
environment:
  height: 4
  width: 4
  start_pos: [0, 0]
  max_steps: 50
  eat_action_enabled: false
  rest_action_enabled: false
  resources:
    - name: "Goal (Food)"
      type: "food"
      count: 1
      spawn_area: [[3, 3], [3, 3]]
      properties: [1.0, 0.0, 0.0, 0.0, 0.0]
      max_consumption: -1
      regeneration_delay: 0
      damage: 0.0
  predator_enabled: false
  predators: []

body:
  with_satiation: false
  with_injury: false
  use_homeostatic_reward: false

sensory:
  using_sensory: false
