# Level 01: Goal Only
environment:
  max_steps: 200
  prob_switch_to_danger: 0.0
  prob_switch_to_food: 1.0
  relocate_resource: false
  eat_action_enabled: false
  rest_action_enabled: false

body:
  with_satiation: false
  with_injury: false
  use_homeostatic_reward: false

sensory:
  using_sensory: false

predator:
  enabled: false
