# Level 03: Dynamic Fixed (Survival)
# Reward: External (Survival)
environment:
  max_steps: 200
  prob_switch_to_danger: 0.1
  prob_switch_to_food: 0.5
  relocate_resource: false
  eat_action_enabled: false
  rest_action_enabled: false

body:
  with_satiation: false
  with_health: false
  use_homeostatic_reward: false
  injury_smoothing_duration: 3

sensory:
  using_sensory: false
