# Level 03: Predator Intro (Instant Death)
environment:
  height: 4
  width: 4
  start_pos: [0, 0]
  max_steps: 100
  eat_action_enabled: false
  rest_action_enabled: false
  resources: []

body:
  with_satiation: false
  with_injury: false
  use_homeostatic_reward: false

sensory:
  using_sensory: false

predator:
  enabled: true
  move_interval: 2
  damage: 100.0
  start_pos: [3, 3]
  random_start_pos: false
  property: [0.0, 1.0, 0.0, 0.0, 0.0]
