# Level 05: Homeostasis (+Olfactory)
environment:
  prob_switch_to_danger: 0.0

body:
  use_homeostatic_reward: false

sensory:
  proprioception_enabled: false
  collision_sensor_enabled: false
  location_sensor: false
