# Default Configuration for GridWorld Interoceptive AI

environment:
  height: 4
  width: 4
  start_pos: [0, 0]
  resource_pos: [3, 3]
  max_steps: 500
  prob_switch_to_danger: 0.1
  min_danger_duration: 5
  damage_amount: 5
  prob_switch_to_food: 0.5
  min_food_duration: 10
  relocate_resource: true  
  relocation_steps: 50

body:
  # Rewards
  death_penalty: 100
  use_homeostatic_reward: false 

  # Satiation
  with_satiation: true
  max_satiation: 30
  satiation_setpoint: 30
  overeating_death: false
  random_start_satiation: true
  start_satiation: 30
  food_satiation_gain: 10
  
  # Health
  with_health: true
  max_health: 20
  start_health_random: false
  start_health: 20
  health_recovery: 1


sensory:
  using_sensory: true
  sensor_radius: 5 # Default: 2
  nociceptor_radius: 0 # Default: 0 (Contact only)
  # Decay Formula: decay = 1.0 / (distance ** decay_power)
  decay_power: 1.0 
  vector_size: 5
  food_property: [1.0, 0.0, 0.0, 0.0, 0.0]
  danger_property: [0.0, 1.0, 0.0, 0.0, 0.0]
  
  # Collision Sensor
  collision_sensor_enabled: true
  collision_sensor_range: 2  # Range of rays in grid cells




