# Level 04: Nociception (Homeostatic - Smooth Injury)
environment:
  resource_pos: [-1, -1] # No Food/Danger on grid
  prob_switch_to_danger: 0.0
  prob_switch_to_food: 0.0
  relocate_resource: false
  eat_action_enabled: false
  rest_action_enabled: true

body:
  with_satiation: false
  with_injury: true
  use_homeostatic_reward: true

sensory:
  using_sensory: true
  olfactory_enabled: false
  proprioception_enabled: false
  collision_sensor_enabled: false
  location_sensor: false
  nociception_enabled: true

predator:
  enabled: true
  damage: 3.0
