# Level 07: +Collision (Homeostatic)
# Reward: Homeostatic (Drive Reduction)
environment:
  max_steps: 200
  prob_switch_to_danger: 0.1
  prob_switch_to_food: 0.5
  relocate_resource: false
  eat_action_enabled: false
  rest_action_enabled: true

body:
  with_satiation: false
  with_health: true
  health_recovery: 2.0
  use_homeostatic_reward: true
  injury_smoothing_duration: 3

sensory:
  using_sensory: true
  nociception_enabled: true
  nociception_size: 1
  olfactory_enabled: true
  proprioception_enabled: true
  collision_sensor_enabled: true
  location_sensor: false
