# Level 07: +Collision (Homeostatic)
# Reward: Homeostatic (Drive Reduction)
environment:
  max_steps: 500
  relocate_resource: true
  eat_action_enabled: true
  rest_action_enabled: true

body:
  with_satiation: true
  with_health: true
  use_homeostatic_reward: true
  satiation_setpoint: 15.0

sensory:
  using_sensory: true
  nociception_enabled: true
  olfactory_enabled: true
  proprioception_enabled: true
  collision_sensor_enabled: true
  collision_sensor_range: 2
  location_sensor: false
