"""CP3b state-evolution bit-identity tests for src/algorithms/dreamer_srl/buffers.py.

CP3b tests state-evolution bit-identity, NOT pure-function bit-identity.
Pure-function identity is impossible here because PyTorch and JAX use different
PRNG streams (D-002 class). Instead these tests:

  - Drive both buffers with an identical deterministic add() sequence and
    compare stored state byte-for-byte.
  - Pre-compute sheeprl's sample-index sequence, pass it to both buffers'
    _sample_at_indices() method, and compare byte-for-byte.
  - Verify is_first marker placement in straddling windows.
  - Verify parallel-env lane non-interference.
  - Verify YAML cadence keys match sheeprl XS defaults.
  - Verify (env_step, grad_step) trace is bit-identical to sheeprl for 5000 iters.

The fixtures are generated by scripts/fixtures/gen_cp3b_fixtures.py (requires
sheeprl_bridge env with PyTorch). Tests run in grid_world_pain env (no PyTorch
needed) and compare against pre-stored reference values.

Run with:
    /home/vncuser/miniconda3/envs/grid_world_pain/bin/python \\
        -m pytest tests/algorithms/dreamer_srl/test_buffers.py -v

DEVIATION NOTES:
  D-004: memmap / memmap_dir / memmap_mode are omitted from the JAX buffer.
    In-memory storage only. See DEVIATION_LOG.md.
"""
import os
import sys

import numpy as np
import pytest
import yaml

_REPO_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
sys.path.insert(0, _REPO_ROOT)

from src.algorithms.dreamer_srl.buffers import SequentialReplayBuffer
from src.algorithms.dreamer_srl.utils import Ratio

FIXTURE_DIR = os.path.join(_REPO_ROOT, "tests", "fixtures", "dreamer_srl")
THRESHOLD = 1e-6


def _load(name: str) -> np.lib.npyio.NpzFile:
    path = os.path.join(FIXTURE_DIR, name)
    if not os.path.exists(path):
        pytest.skip(f"Fixture not found: {path}. Run scripts/fixtures/gen_cp3b_fixtures.py first.")
    return np.load(path)


# ---------------------------------------------------------------------------
# Test 1: buffer_storage_state_after_deterministic_adds
# ---------------------------------------------------------------------------

def test_buffer_state_evolution_matches_sheeprl():
    """Drive our JAX buffer with the same add() sequence as sheeprl.

    Both buffers receive the same 100-step add() sequence from fixture.
    Assert byte-identical storage state (_buf, _pos, _full).

    Catches: any add() ring-buffer arithmetic divergence from sheeprl.

    CP3b Lever-A test 1.
    Sheeprl source: vendor/sheeprl/sheeprl/data/buffers.py:L145-L221
    """
    f = _load("buffer_storage_state_after_deterministic_adds_input.npz")

    buffer_size = int(f["buffer_size"])
    n_envs = int(f["n_envs"])
    n_steps = int(f["n_steps"])
    expected_pos = int(f["sheeprl_pos"])
    expected_full = bool(f["sheeprl_full"])

    # Reconstruct the step sequence
    step_keys = ["observations", "actions", "rewards", "terminated", "truncated", "is_first"]
    steps = []
    for i in range(n_steps):
        step = {}
        for k in step_keys:
            arr = f[f"step_{k}"]  # shape [n_steps, 1, n_envs, ...]
            step[k] = arr[i]  # shape [1, n_envs, ...]
        steps.append(step)

    # Drive our JAX buffer
    jax_rb = SequentialReplayBuffer(buffer_size=buffer_size, n_envs=n_envs)
    for step in steps:
        jax_rb.add(step)

    # Assert metadata matches
    assert jax_rb._pos == expected_pos, f"_pos mismatch: got {jax_rb._pos}, expected {expected_pos}"
    assert jax_rb._full == expected_full, f"_full mismatch: got {jax_rb._full}, expected {expected_full}"

    # Assert stored buffer arrays are byte-identical in the FILLED region.
    # Both buffers allocate with np.empty so the unfilled portion [_pos:] is
    # uninitialized garbage — we compare only [:_pos] which has been written.
    for k in step_keys:
        sheeprl_arr = np.asarray(f[f"buf_{k}"])  # shape [buffer_size, n_envs, ...]
        jax_arr = jax_rb._buf[k]
        assert jax_arr.shape == sheeprl_arr.shape, (
            f"Shape mismatch for '{k}': jax={jax_arr.shape}, sheeprl={sheeprl_arr.shape}"
        )
        # Compare only the filled region (semantically equivalent to sheeprl)
        n_filled = expected_pos  # _pos == number of steps added when _full is False
        sheeprl_filled = sheeprl_arr[:n_filled]
        jax_filled = jax_arr[:n_filled]
        max_abs_diff = float(np.max(np.abs(jax_filled - sheeprl_filled)))
        assert max_abs_diff < THRESHOLD, (
            f"Buffer state diverges for '{k}' (filled region [:{ n_filled}]): "
            f"max_abs_diff={max_abs_diff:.3e} >= {THRESHOLD:.1e}"
        )


# ---------------------------------------------------------------------------
# Test 2: buffer_sample_at_indices_matches_sheeprl
# ---------------------------------------------------------------------------

def test_buffer_indexed_sample_matches_sheeprl():
    """Pre-compute sheeprl's sample-index sequence, apply both buffers' index-selection path.

    Bypasses PRNG entirely — pre-computed start_idxes and env_idxes from
    sheeprl's RNG are stored in the fixture. Our JAX buffer's
    _sample_at_indices() receives the same indices. Assert byte-identical output.

    Catches: any _get_samples reshape/tile/flatten divergence from sheeprl.
    The PRNG divergence (D-002) is bypassed — this is the testable part.

    CP3b Lever-A test 2.
    Sheeprl source: vendor/sheeprl/sheeprl/data/buffers.py:L467-L526
    """
    f = _load("buffer_sample_at_indices_matches_sheeprl_input.npz")

    buffer_size = int(f["buffer_size"])
    n_envs = int(f["n_envs"])
    n_steps = int(f["n_steps"])
    sequence_length = int(f["sequence_length"])
    batch_size = int(f["batch_size"])
    n_samples = int(f["n_samples"])
    precomputed_start_idxes = f["precomputed_start_idxes"].astype(np.intp)
    precomputed_env_idxes = f["precomputed_env_idxes"].astype(np.intp)

    step_keys = ["observations", "actions", "rewards", "terminated", "truncated", "is_first"]

    # Reconstruct the same buffer
    jax_rb = SequentialReplayBuffer(buffer_size=buffer_size, n_envs=n_envs)
    for i in range(n_steps):
        step = {}
        for k in step_keys:
            arr = f[f"step_{k}"]  # shape [n_steps, 1, n_envs, ...]
            step[k] = arr[i]
        jax_rb.add(step)

    # Call _sample_at_indices with the pre-computed indices
    jax_samples = jax_rb._sample_at_indices(
        precomputed_start_idxes=precomputed_start_idxes,
        env_idxes=precomputed_env_idxes,
        sequence_length=sequence_length,
        batch_size=batch_size,
        n_samples=n_samples,
    )

    # Compare against sheeprl reference
    for k in step_keys:
        sheeprl_sample = np.asarray(f[f"sheeprl_sample_{k}"])
        jax_sample = jax_samples[k]
        assert jax_sample.shape == sheeprl_sample.shape, (
            f"Shape mismatch for '{k}': jax={jax_sample.shape}, sheeprl={sheeprl_sample.shape}"
        )
        max_abs_diff = float(np.max(np.abs(jax_sample - sheeprl_sample)))
        assert max_abs_diff < THRESHOLD, (
            f"_sample_at_indices output diverges for '{k}': "
            f"max_abs_diff={max_abs_diff:.3e} >= {THRESHOLD:.1e}"
        )


# ---------------------------------------------------------------------------
# Test 3: buffer_is_first_marker_placement_in_straddling_window
# ---------------------------------------------------------------------------

def test_is_first_marker_at_done_boundary():
    """Assert is_first=1 lands at the correct time index in a straddling window.

    A buffer is constructed with a done at step DONE_AT and is_first=1 at
    step DONE_AT+1. A window starting at START_IDX straddles the boundary.
    Assert:
      (a) JAX output is byte-identical to sheeprl's.
      (b) is_first[expected_offset] == 1 and all others are 0.

    This catches the silently-dead-CP4b-code-path failure mode: if is_first
    placement diverges, CP4b's three-quantity reset never fires in practice.

    CP3b Lever-A test 3.
    Sheeprl source: vendor/sheeprl/sheeprl/data/buffers.py:L395-L526
    """
    f = _load("buffer_is_first_marker_placement_in_straddling_window_input.npz")

    buffer_size = int(f["buffer_size"])
    n_envs = int(f["n_envs"])
    n_steps = int(f["n_steps"])
    start_idx = int(f["start_idx"])
    sequence_length = int(f["sequence_length"])
    is_first_expected_offset = int(f["is_first_expected_offset"])

    step_keys = ["observations", "actions", "rewards", "terminated", "truncated", "is_first"]

    # Reconstruct JAX buffer with the same step sequence
    jax_rb = SequentialReplayBuffer(buffer_size=buffer_size, n_envs=n_envs)
    for i in range(n_steps):
        step = {}
        for k in step_keys:
            arr = f[f"step_{k}"]  # shape [n_steps, 1, 1, ...]
            step[k] = arr[i]
        jax_rb.add(step)

    # Force-sample the straddling window
    start_idx_arr = np.array([start_idx], dtype=np.intp)
    env_idxes_arr = np.array([0], dtype=np.intp)

    jax_samples = jax_rb._sample_at_indices(
        precomputed_start_idxes=start_idx_arr,
        env_idxes=env_idxes_arr,
        sequence_length=sequence_length,
        batch_size=1,
        n_samples=1,
    )

    # (a) Byte-identical to sheeprl
    for k in step_keys:
        sheeprl_sample = np.asarray(f[f"sheeprl_sample_{k}"])
        jax_sample = jax_samples[k]
        assert jax_sample.shape == sheeprl_sample.shape, (
            f"Shape mismatch for '{k}': jax={jax_sample.shape}, sheeprl={sheeprl_sample.shape}"
        )
        max_abs_diff = float(np.max(np.abs(jax_sample - sheeprl_sample)))
        assert max_abs_diff < THRESHOLD, (
            f"Straddling window diverges for '{k}': "
            f"max_abs_diff={max_abs_diff:.3e} >= {THRESHOLD:.1e}"
        )

    # (b) is_first placement
    # jax_samples["is_first"] shape: [1, seq_len, 1, 1]
    is_first_window = jax_samples["is_first"].ravel()  # shape [seq_len]
    assert is_first_window[is_first_expected_offset] == 1.0, (
        f"is_first=1 not at expected offset {is_first_expected_offset}: {is_first_window}"
    )
    for i, val in enumerate(is_first_window):
        if i != is_first_expected_offset:
            assert val == 0.0, (
                f"Unexpected is_first=1 at offset {i}: {is_first_window}"
            )


# ---------------------------------------------------------------------------
# Test 4: buffer_parallel_env_lane_non_interference
# ---------------------------------------------------------------------------

def test_parallel_env_lane_non_interference():
    """Add 200 transitions across 4 envs. Assert no cross-lane leakage.

    Env 0's obs are all 1.0, env 1's all 2.0, etc.
    Sample contiguous windows from each lane (using _sample_at_indices with
    env_idxes locked to one lane). Assert every obs value in the window
    matches that lane's sentinel value.

    Catches: any cross-env buffer leakage from incorrect n_envs striding.

    CP3b Lever-A test 4.
    Sheeprl source: vendor/sheeprl/sheeprl/data/buffers.py:L480-L489
    """
    f = _load("buffer_parallel_env_lane_non_interference_input.npz")

    buffer_size = int(f["buffer_size"])
    n_envs = int(f["n_envs"])
    n_steps = int(f["n_steps"])
    sequence_length = int(f["sequence_length"])
    n_windows = int(f["n_windows"])

    step_keys = ["observations", "actions", "rewards", "terminated", "truncated", "is_first"]

    # Rebuild JAX buffer
    jax_rb = SequentialReplayBuffer(buffer_size=buffer_size, n_envs=n_envs)
    for i in range(n_steps):
        step = {}
        for k in step_keys:
            arr = f[f"step_{k}"]  # shape [n_steps, 1, n_envs, ...]
            step[k] = arr[i]
        jax_rb.add(step)

    # Sample n_windows windows from each lane with a deterministic start
    # (start_idxes must be valid: [0 .. pos - seq_len])
    max_start = jax_rb._pos - sequence_length  # = 50 - 8 = 42
    start_idxes = np.arange(0, min(n_windows, max_start + 1), dtype=np.intp)

    for env_idx in range(n_envs):
        sentinel = float(env_idx + 1)
        env_idxes = np.full(len(start_idxes), env_idx, dtype=np.intp)

        samples = jax_rb._sample_at_indices(
            precomputed_start_idxes=start_idxes,
            env_idxes=env_idxes,
            sequence_length=sequence_length,
            batch_size=len(start_idxes),
            n_samples=1,
        )

        obs = samples["observations"]  # shape [1, seq_len, batch, obs_dim]
        obs_flat = obs.ravel()
        assert np.allclose(obs_flat, sentinel), (
            f"Env lane {env_idx} (sentinel={sentinel}) has contaminated obs. "
            f"Unique values found: {np.unique(obs_flat)}"
        )


# ---------------------------------------------------------------------------
# Test 5: cadence_yaml_key_parity_with_sheeprl_xs
# ---------------------------------------------------------------------------

def test_cadence_yaml_key_parity_vs_sheeprl_xs():
    """Load agent_xs.yaml and assert exact-match against sheeprl XS defaults.

    The 9 cadence keys are hard-coded in the assertion; their canonical source
    is sheeprl's dreamer_v3.yaml / exp/dreamer_v3.yaml / env/default.yaml at
    commit 33b6366. If sheeprl ever bumps a default, this test breaks loudly.

    CP3b Lever-A test 5 (cadence sub-gate).
    Sheeprl sources:
      vendor/sheeprl/sheeprl/configs/algo/dreamer_v3.yaml
      vendor/sheeprl/sheeprl/configs/exp/dreamer_v3.yaml
      vendor/sheeprl/sheeprl/configs/env/default.yaml
    """
    yaml_path = os.path.join(_REPO_ROOT, "configs", "dreamer_srl", "agent_xs.yaml")
    if not os.path.exists(yaml_path):
        pytest.skip(f"Config not found: {yaml_path}")

    with open(yaml_path) as fh:
        cfg = yaml.safe_load(fh)

    algo = cfg.get("algo", {})
    env = cfg.get("env", {})
    critic = algo.get("critic", {})

    # Hard-coded sheeprl XS defaults (canonical source cited above)
    assert algo.get("learning_starts") == 1024, (
        f"learning_starts mismatch: got {algo.get('learning_starts')}, expected 1024"
    )
    assert algo.get("replay_ratio") == 1, (
        f"replay_ratio mismatch: got {algo.get('replay_ratio')}, expected 1"
    )
    assert algo.get("per_rank_gradient_steps") == 1, (
        f"per_rank_gradient_steps mismatch: got {algo.get('per_rank_gradient_steps')}, expected 1"
    )
    assert algo.get("per_rank_sequence_length") == 64, (
        f"per_rank_sequence_length mismatch: got {algo.get('per_rank_sequence_length')}, expected 64"
    )
    assert algo.get("per_rank_batch_size") == 16, (
        f"per_rank_batch_size mismatch: got {algo.get('per_rank_batch_size')}, expected 16"
    )
    assert algo.get("per_rank_pretrain_steps") == 0, (
        f"per_rank_pretrain_steps mismatch: got {algo.get('per_rank_pretrain_steps')}, expected 0"
    )
    assert critic.get("per_rank_target_network_update_freq") == 1, (
        f"per_rank_target_network_update_freq mismatch: "
        f"got {critic.get('per_rank_target_network_update_freq')}, expected 1"
    )
    assert algo.get("total_steps") == 5000000, (
        f"total_steps mismatch: got {algo.get('total_steps')}, expected 5000000"
    )
    assert env.get("num_envs") == 1, (
        f"num_envs mismatch: got {env.get('num_envs')}, expected 1"
    )


# ---------------------------------------------------------------------------
# Test 6: cadence_env_grad_step_trace_5000_iters
# ---------------------------------------------------------------------------

def test_env_grad_step_trace_matches_sheeprl():
    """For a fixed seed + XS config, assert (env_step, grad_step, per_rank_gradient_steps)
    trace is bit-identical to sheeprl for 5000 iterations.

    Catches the 16× replay-ratio-class divergence at design time:
    if Ratio semantics, learning_starts arithmetic, or prefill_steps are wrong,
    the cumulative grad_step count will diverge from sheeprl's.

    The trace is compared against the pre-computed sheeprl reference in the fixture
    (generated by gen_cp3b_fixtures.py using sheeprl's Ratio class directly).

    CP3b Lever-A test 6 (cadence sub-gate).
    Sheeprl source: vendor/sheeprl/sheeprl/algos/dreamer_v3/dreamer_v3.py:L505-L515,
                    L550-L551, L661-L662
    """
    f = _load("cadence_env_grad_step_trace_5000_iters_input.npz")

    num_envs = int(f["num_envs"])
    world_size = int(f["world_size"])
    total_iters = int(f["total_iters"])
    replay_ratio = float(f["replay_ratio"])
    learning_starts_steps = int(f["learning_starts_steps"])
    per_rank_pretrain_steps = int(f["per_rank_pretrain_steps"])
    expected_trace = f["expected_trace"]  # shape [total_iters, 3]: (env_step, grad_step, per_rank_gs)

    # Replicate sheeprl cadence arithmetic using our Ratio class
    # Ref: dreamer_v3.py:L505-L515
    policy_steps_per_iter = int(num_envs * world_size)  # = 1
    learning_starts = learning_starts_steps // policy_steps_per_iter  # = 1024
    prefill_steps = learning_starts - int(learning_starts > 0)  # = 1023

    ratio = Ratio(replay_ratio, pretrain_steps=per_rank_pretrain_steps)

    policy_step = 0
    cumulative_grad_steps = 0
    jax_trace = []

    for iter_num in range(1, total_iters + 1):
        policy_step += policy_steps_per_iter

        per_rank_gradient_steps = 0
        if iter_num >= learning_starts:
            # Ref: dreamer_v3.py:L661-L662
            ratio_steps = policy_step - prefill_steps * policy_steps_per_iter
            per_rank_gradient_steps = ratio(ratio_steps / world_size)
            cumulative_grad_steps += per_rank_gradient_steps

        jax_trace.append((policy_step, cumulative_grad_steps, per_rank_gradient_steps))

    jax_trace_arr = np.array(jax_trace, dtype=np.int64)

    assert jax_trace_arr.shape == expected_trace.shape, (
        f"Trace shape mismatch: jax={jax_trace_arr.shape}, expected={expected_trace.shape}"
    )

    # Bit-identical check
    mismatch = np.where(jax_trace_arr != expected_trace)
    if len(mismatch[0]) > 0:
        first_mismatch = mismatch[0][0]
        col_names = ["env_step", "grad_step", "per_rank_gradient_steps"]
        col = mismatch[1][0]
        pytest.fail(
            f"Cadence trace diverges from sheeprl at iter {first_mismatch + 1}, "
            f"column '{col_names[col]}': "
            f"jax={jax_trace_arr[first_mismatch, col]}, "
            f"sheeprl={expected_trace[first_mismatch, col]}\n"
            f"First 5 jax:     {jax_trace_arr[:5].tolist()}\n"
            f"First 5 sheeprl: {expected_trace[:5].tolist()}\n"
            "HALT: This is the 16x replay-ratio-class divergence. "
            "Do not relax threshold — investigate the root cause."
        )
