"""CP5 bit-identity tests for src/algorithms/dreamer_srl/loss.py.

Tests the TwoHotEncoding class ported from
sheeprl@33b6366:sheeprl/utils/distribution.py:L224-L276.

Each test asserts that the JAX implementation agrees with the pre-computed
sheeprl@33b6366 PyTorch reference (stored in tests/fixtures/dreamer_srl/*.npz)
to within 1e-6 max-absolute-difference (Lever A in
docs/develop/active/dreamer_srl_v1/IMPLEMENTATION_PLAN.md).

The fixtures are generated by scripts/fixtures/gen_cp5_fixtures.py which runs
in the sheeprl_bridge env (has PyTorch). The tests here run in the grid_world_pain
env (JAX only) and compare against the pre-stored torch_out values.

Run with:
    /home/vncuser/miniconda3/envs/grid_world_pain/bin/python \\
        -m pytest tests/algorithms/dreamer_srl/test_loss.py -v

HISTORICAL SCAR — WHY THESE TESTS EXIST
-----------------------------------------
During the v1 cascade debugging (pre-2026-05-12), the bin grid was implemented
in real reward space (self.bins = symexp(linspace(-20, 20, 255))). Losses
decreased but to the wrong basin. Static plan review (three reviewers, 1056-line
spec) did not catch it. test_twohot_encode_matches_sheeprl (Test 2) with a
non-trivial target (e.g. target=0.5, symlog(0.5)≈0.405) would have caught the
bug on the first run: the bin indices would be wrong, the two-hot weights would
differ, and log_prob would mismatch by orders of magnitude.

SYMLOG-SPACE BIN DISCIPLINE
----------------------------
The bin grid linspace(-20, 20, 255) is stored in SYMLOG SPACE. symexp is applied
ONLY at consumption (mean/mode), never to the stored grid. Targets are
symlog-encoded BEFORE bin lookup inside log_prob. All three tests verify this
discipline holds.

THRESHOLD NOTE
--------------
Two-hot encoding is integer-arithmetic-heavy (one_hot scatter + integer bin
indices). The expected max_abs_diff is well below 1e-6. No deviation-log entry
is expected. If any test exceeds 1e-6 and it is not a platform float32 ULP
issue, the deviation must be logged in DEVIATION_LOG.md before proceeding.
"""
import os
import sys

import numpy as np
import pytest

# Ensure repo root is on sys.path for src.* imports
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.insert(0, _REPO_ROOT)

import jax.numpy as jnp

from src.algorithms.dreamer_srl.loss import TwoHotEncoding

FIXTURE_DIR = os.path.join(_REPO_ROOT, "tests", "fixtures", "dreamer_srl")
THRESHOLD = 1e-6  # default Lever A threshold

# D-006: JAX jnp.linspace vs PyTorch torch.linspace ULP difference.
# bins[127]: JAX=0.0 exactly, PyTorch=7.45e-8 (1 ULP at the midpoint step 40/254*127).
# This cascades: bins max_abs_diff=1.9e-6, encode=6.1e-6, log_prob=1.8e-5.
# Relative max diff for log_prob: 2.4e-6 — float32 linspace + arithmetic platform drift.
# Threshold relaxed to 3e-5 (same order as D-003 symexp ULP drift).
# Pending PI sign-off at CP5 gate. See DEVIATION_LOG.md D-006.
THRESHOLD_D006 = 3e-5


def _load(name: str) -> np.lib.npyio.NpzFile:
    path = os.path.join(FIXTURE_DIR, name)
    if not os.path.exists(path):
        pytest.skip(f"Fixture not found: {path}. Run scripts/fixtures/gen_cp5_fixtures.py first.")
    return np.load(path)


# ---------------------------------------------------------------------------
# Test 1 — twohot_bins_endpoints
# ---------------------------------------------------------------------------

def test_twohot_bins_endpoints_match_sheeprl():
    """Verify bin grid endpoints and the full 255-bin grid match sheeprl's.

    Lever A test for CP5 function 'twohot_bins_endpoints'.
    Sheeprl source: vendor/sheeprl/sheeprl/utils/distribution.py:L237

    Asserts:
      - jax.bins[0] == -20.0   (exact — float32 linspace boundary)
      - |jax.bins[127]| < 1e-6 (float32 linspace midpoint; 7.45e-08 due to rounding)
      - jax.bins[254] == +20.0 (exact — float32 linspace boundary)
      - max_abs_diff(jax.bins, sheeprl.bins) < 1e-6 over the full 255-bin grid

    NOTE: bins[127] is NOT exactly 0.0 in sheeprl's float32 linspace. The value
    is 7.45e-08 (one float32 ULP from zero at the scale of linspace(-20,20,255)).
    Both sides reproduce this identical float32 rounding, so max_abs_diff = 0.0.
    Do NOT change the threshold or "fix" bins[127] to 0.0 — that would diverge.

    Historical scar context: if the JAX implementation used symexp(linspace(...))
    instead of linspace(...), this test would catch it immediately because
    symexp(-20)≠-20 and symexp(20)≠20 in real space.
    """
    fixture = _load("twohot_bins_endpoints_input.npz")
    torch_bins = fixture["torch_bins"]  # [255] from sheeprl PyTorch

    # Instantiate with dummy logits of shape [1, 255] to access .bins
    dummy_logits = jnp.zeros((1, 255))
    jax_dist = TwoHotEncoding(dummy_logits, dims=0, low=-20, high=20)
    jax_bins = jax_dist.bins  # [255]

    # Endpoint checks
    assert float(jax_bins[0]) == -20.0, f"bins[0] must be -20.0, got {float(jax_bins[0])}"
    assert abs(float(jax_bins[127])) < 1e-6, (
        f"bins[127] must be ~0.0 (|val| < 1e-6), got {float(jax_bins[127])}. "
        f"If this fails, the bin grid may be in real space (historical bug)."
    )
    assert float(jax_bins[254]) == 20.0, f"bins[254] must be +20.0, got {float(jax_bins[254])}"

    # Full grid bit-identity against sheeprl.
    # D-006: JAX linspace and PyTorch linspace differ by 1 ULP at the midpoint.
    # Threshold relaxed to THRESHOLD_D006=3e-5. Pending PI sign-off at CP5 gate.
    max_abs_diff = float(jnp.max(jnp.abs(jax_bins - jnp.asarray(torch_bins))))
    assert max_abs_diff < THRESHOLD_D006, (
        f"twohot_bins_endpoints max_abs_diff={max_abs_diff:.3e} exceeds D-006 threshold {THRESHOLD_D006:.1e}. "
        f"Bin grid does not match sheeprl. "
        f"D-006: JAX/PyTorch linspace ULP diff at midpoint is expected (~1.9e-6). "
        f"If diff > 3e-5, a semantic error has been introduced — log in DEVIATION_LOG.md."
    )


# ---------------------------------------------------------------------------
# Test 2 — twohot_encode
# ---------------------------------------------------------------------------

def test_twohot_encode_matches_sheeprl():
    """Verify two-hot encoding of a [T=4, B=16, 1] target batch matches sheeprl.

    Lever A test for CP5 function 'twohot_encode'.
    Sheeprl source: vendor/sheeprl/sheeprl/utils/distribution.py:L253-L274

    THIS IS THE TEST THAT CATCHES THE HISTORICAL BUG.
    If the JAX implementation stores bins in real reward space instead of symlog
    space, the bin indices (below/above) are computed against the wrong grid,
    producing wrong two-hot weights. The max_abs_diff would be orders of magnitude
    above 1e-6 for any non-trivial target.

    The test exposes the raw two-hot target (weights over 255 bins) by calling
    log_prob with arbitrary uniform logits so that log_pred ≈ log(1/255) everywhere
    — dividing by that constant recovers the two-hot distribution up to normalization.
    Instead, we directly compare the two-hot encoding by using the fixture's
    pre-computed torch_out_twohot (the raw two-hot target [T,B,255]).

    We recover the JAX two-hot target by computing log_prob with logits=zeros
    (so log_pred = -log(255) everywhere) and verifying the result matches
    the fixture's log_prob. The fixture also stores torch_out_twohot directly
    for structural verification.
    """
    fixture = _load("twohot_encode_input.npz")
    logits_np = fixture["logits"]           # [T=4, B=16, 255]
    targets_np = fixture["targets"]         # [T=4, B=16, 1]
    torch_twohot = fixture["torch_out_twohot"]  # [T=4, B=16, 255]

    # Compute the JAX two-hot encoding by replicating the internal logic.
    # We expose the two-hot target by using log(1/255) everywhere:
    #   log_prob = (target * log_pred).sum(axis=dims)
    # With logits = zeros, log_pred = -log(255) at every bin, so:
    #   log_prob = -log(255) * target.sum() = -log(255) (since target is a distribution)
    # That would give a scalar; instead we directly verify by building the JAX
    # TwoHotEncoding with the actual logits and then extracting the two-hot target
    # from the log_prob arithmetic.
    #
    # Cleaner: use logits = zeros to get log_pred = const, then log_prob / const = target.sum()
    # But even cleaner: replicate the two-hot target computation directly in JAX and compare.

    # Build JAX dist with actual logits (for structural verification)
    logits_jax = jnp.asarray(logits_np)
    targets_jax = jnp.asarray(targets_np)

    jax_dist = TwoHotEncoding(logits_jax, dims=1, low=-20, high=20)
    n_bins = jax_dist.bins.shape[0]

    # Replicate the two-hot target computation (same code path as log_prob,
    # but exposed for direct comparison against torch_out_twohot).
    # Ported from sheeprl@33b6366:sheeprl/utils/distribution.py:L254-L274
    from src.algorithms.dreamer_srl.utils import symlog
    x = symlog(targets_jax)  # symlog-encode target before bin lookup

    below = (jax_dist.bins <= x).astype(jnp.int32).sum(axis=-1, keepdims=True) - 1
    above = below + 1
    above = jnp.minimum(above, n_bins - 1)
    below = jnp.maximum(below, 0)
    equal = below == above
    dist_to_below = jnp.where(equal, jnp.ones_like(x), jnp.abs(jax_dist.bins[below] - x))
    dist_to_above = jnp.where(equal, jnp.ones_like(x), jnp.abs(jax_dist.bins[above] - x))
    total = dist_to_below + dist_to_above
    weight_below = dist_to_above / total
    weight_above = dist_to_below / total
    jax_twohot = (
        jax.nn.one_hot(below, n_bins) * weight_below[..., None]
        + jax.nn.one_hot(above, n_bins) * weight_above[..., None]
    )
    jax_twohot = jnp.squeeze(jax_twohot, axis=-2)  # [T, B, 255]

    # D-006: linspace ULP cascades from bins into the weight computation.
    # Expected max_abs_diff ~6.1e-6; threshold THRESHOLD_D006=3e-5.
    # Historical-bug scale would be >> 0.1 (bins in real space → completely wrong indices).
    max_abs_diff = float(jnp.max(jnp.abs(jax_twohot - jnp.asarray(torch_twohot))))
    assert max_abs_diff < THRESHOLD_D006, (
        f"twohot_encode max_abs_diff={max_abs_diff:.3e} exceeds D-006 threshold {THRESHOLD_D006:.1e}. "
        f"If diff > 0.1: likely the historical bug (bins in real space, not symlog space). "
        f"If diff < 3e-5: the D-006 float32 linspace ULP cascade is expected. "
        f"Check that loss.py does NOT apply symexp to self.bins at storage."
    )


# ---------------------------------------------------------------------------
# Test 3 — twohot_log_prob
# ---------------------------------------------------------------------------

def test_twohot_log_prob_matches_sheeprl():
    """Verify log_prob(target) for [T=4, B=16, 1] targets matches sheeprl output.

    Lever A test for CP5 function 'twohot_log_prob'.
    Sheeprl source: vendor/sheeprl/sheeprl/utils/distribution.py:L253-L276

    This test exercises both the encoding (Test 2 prerequisite) AND the
    log-pred computation (logsumexp normalization + cross-entropy reduction).
    If the log_prob matches sheeprl exactly, both the symlog-space bin lookup
    AND the log-probability arithmetic are correct.

    Expected shape: [T=4, B=16] (event dim dims=1 reduced out).
    Expected max_abs_diff < 1e-6 (no D-class deviation anticipated).
    """
    fixture = _load("twohot_log_prob_input.npz")
    logits_np = fixture["logits"]           # [T=4, B=16, 255]
    targets_np = fixture["targets"]         # [T=4, B=16, 1]
    torch_log_prob = fixture["torch_out_log_prob"]  # [T=4, B=16]

    logits_jax = jnp.asarray(logits_np)
    targets_jax = jnp.asarray(targets_np)

    jax_dist = TwoHotEncoding(logits_jax, dims=1, low=-20, high=20)
    jax_log_prob = jax_dist.log_prob(targets_jax)  # [T, B]

    # Shape check
    assert jax_log_prob.shape == torch_log_prob.shape, (
        f"Shape mismatch: jax={jax_log_prob.shape} torch={torch_log_prob.shape}. "
        f"dims=1 must reduce the event dimension [T,B,1] → [T,B]."
    )

    # D-006: linspace ULP cascades from bins → encode → log_prob sum.
    # Expected max_abs_diff ~1.8e-5 (relative: 2.4e-6 — float32 platform drift).
    # Threshold THRESHOLD_D006=3e-5. Pending PI sign-off at CP5 gate.
    max_abs_diff = float(jnp.max(jnp.abs(jax_log_prob - jnp.asarray(torch_log_prob))))
    assert max_abs_diff < THRESHOLD_D006, (
        f"twohot_log_prob max_abs_diff={max_abs_diff:.3e} exceeds D-006 threshold {THRESHOLD_D006:.1e}. "
        f"Expected ~1.8e-5 (D-006 float32 linspace ULP cascade). "
        f"Check: (1) symlog applied to x before bin lookup, (2) bins in symlog space, "
        f"(3) logsumexp normalization matches sheeprl L275. "
        f"Log in DEVIATION_LOG.md if unavoidable."
    )


# ---------------------------------------------------------------------------
# Safety check — verify isolation rule
# ---------------------------------------------------------------------------

def test_loss_module_does_not_import_from_src_models():
    """Verify loss.py does not import from src.models (isolation rule).

    Imports from src.models.dreamer_v3_* are forbidden in src/algorithms/dreamer_srl/
    (v2 Risks §13). The historical bug in part arose from pattern-matching against
    the in-house code that had bins in real reward space.
    """
    import importlib
    import importlib.util
    import ast

    loss_path = os.path.join(_REPO_ROOT, "src", "algorithms", "dreamer_srl", "loss.py")
    with open(loss_path) as f:
        source = f.read()

    tree = ast.parse(source)
    forbidden_imports = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if isinstance(node, ast.ImportFrom) and node.module:
                if "src.models.dreamer_v3" in node.module:
                    forbidden_imports.append(node.module)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    if "src.models.dreamer_v3" in alias.name:
                        forbidden_imports.append(alias.name)

    assert not forbidden_imports, (
        f"loss.py imports from forbidden modules: {forbidden_imports}. "
        f"Isolation rule (v2 Risks §13): src/algorithms/dreamer_srl/ must not "
        f"import from src.models.dreamer_v3_*."
    )


# Guard against symexp-at-storage regression
def test_bins_not_symexp_at_storage():
    """Verify bins are NOT symexp-transformed at storage time.

    The historical bug stored self.bins = symexp(linspace(-20, 20, 255)).
    This test catches that recurrence: if symexp were applied at storage,
    bins[0] would be symexp(-20) ≈ -485165195 not -20.0.

    This test is structurally redundant with test_twohot_bins_endpoints_match_sheeprl
    but makes the historical-bug-prevention intent explicit.
    """
    dummy_logits = jnp.zeros((1, 255))
    jax_dist = TwoHotEncoding(dummy_logits, dims=0, low=-20, high=20)

    # If symexp were applied at storage: symexp(-20) ≈ -485165195
    # If bins are in symlog space: bins[0] = -20.0
    assert abs(float(jax_dist.bins[0]) - (-20.0)) < 1e-6, (
        f"bins[0] = {float(jax_dist.bins[0]):.6f}, expected -20.0. "
        f"If this is ~-485165195, symexp was incorrectly applied at storage — "
        f"that is the historical bug. bins must stay in symlog space."
    )
    assert abs(float(jax_dist.bins[254]) - 20.0) < 1e-6, (
        f"bins[254] = {float(jax_dist.bins[254]):.6f}, expected +20.0. "
        f"If this is ~+485165195, symexp was incorrectly applied at storage."
    )


# Need jax.nn for the test
import jax  # noqa: E402 — after src imports to avoid shadowing


# ---------------------------------------------------------------------------
# WP-SRL P3 — SymlogDistribution + faithful obs-loss routing
# (fix_plan_srl_parity.md; area report 02_world_model_losses rows 6-8, 22)
#
# Red evidence (pre-fix): these three tests fail at collection with
# ImportError — SymlogDistribution does not exist ("red by absence").
# The 2x ratio test additionally encodes the audited measured ratio
# (area report 02 measured old/new = 0.500000).
# ---------------------------------------------------------------------------

def test_symlog_distribution_matches_reference_formula():
    """SymlogDistribution.log_prob == -sum(where(dist^2 < tol, 0, dist^2)).

    Reference: vendor/sheeprl/sheeprl/utils/distribution.py:L152-L193
    (SymlogDistribution, dist="mse", agg="sum" branch): the raw decoder
    output IS the symlog-space prediction; log_prob compares it to
    symlog(value); squared distances below tol=1e-8 are zeroed
    (distribution.py:159, 181 — audit row 8's missing clamp).

    Fixture includes sub-tolerance elements (|pred - symlog(target)| = 1e-5,
    squared 1e-10 < 1e-8) to exercise the clamp branch.
    """
    from src.algorithms.dreamer_srl.loss import SymlogDistribution
    from src.algorithms.dreamer_srl.utils import symexp, symlog

    rng = np.random.default_rng(0xD3EAF)
    T, B, D = 4, 3, 6
    pred = jnp.asarray(rng.standard_normal((T, B, D)), dtype=jnp.float32)
    target = jnp.asarray(rng.standard_normal((T, B, D)) * 5.0, dtype=jnp.float32)
    # Force sub-tol residuals at a few positions: target = symexp(pred + 1e-5)
    # -> (pred - symlog(target))^2 ~ 1e-10 < tol=1e-8 -> zeroed by the clamp.
    sub_tol_target = symexp(pred + 1e-5)
    mask = np.zeros((T, B, D), dtype=bool)
    mask[0, 0, :] = True    # FULL row sub-tol: clamped log_prob[0, 0] == -0.0 exactly
    mask[2, 1, 2:5] = True
    target = jnp.where(jnp.asarray(mask), sub_tol_target, target)

    dist = SymlogDistribution(pred, dims=1)
    got = dist.log_prob(target)  # [T, B]

    distance = np.asarray((pred - symlog(target)) ** 2)
    distance = np.where(distance < 1e-8, 0.0, distance)
    want = -distance.sum(axis=-1)  # [T, B]

    assert got.shape == (T, B)
    max_diff = float(np.max(np.abs(np.asarray(got) - want)))
    assert max_diff < 1e-6, (
        f"SymlogDistribution.log_prob deviates from the reference formula by "
        f"{max_diff:.3e} (tol-clamp or sum-dims drift)."
    )
    # The clamp must actually fire. In float32 a ~1e-10 residual is absorbed
    # when summed with O(1) terms, so the discriminating cell is the FULL
    # sub-tol row [0, 0]: with the clamp its log_prob is exactly -0.0; without
    # the clamp it is ~ -D * 1e-10 != 0.
    no_clamp_row00 = float(-np.asarray((pred - symlog(target)) ** 2)[0, 0].sum())
    assert float(np.asarray(got)[0, 0]) == 0.0, (
        f"log_prob[0, 0] = {float(np.asarray(got)[0, 0])!r}, expected exact "
        "0.0 for a full sub-tol row — the tol=1e-8 clamp is not firing "
        "(audit row 8 regression)."
    )
    assert no_clamp_row00 != 0.0, (
        "Fixture drift: the unclamped full sub-tol row sums to exactly zero, "
        "so the clamp check is vacuous. Re-derive the fixture."
    )

    # mode/mean apply symexp at consumption (distribution.py:170-175).
    np.testing.assert_allclose(
        np.asarray(dist.mode), np.asarray(symexp(pred)), rtol=1e-6
    )
    np.testing.assert_allclose(
        np.asarray(dist.mean), np.asarray(symexp(pred)), rtol=1e-6
    )


def test_obs_loss_exactly_2x_old_inline():
    """The faithful obs NLL is exactly 2x the deleted inline formula.

    The pre-fix inline assembly (train.py:709-711) computed
        old = 0.5 * sum((symlog(recon) - symlog(target))^2)
    i.e. a Normal(., 1) log-density with its -0.5 factor — under-weighting
    reconstruction exactly 2x vs sheeprl's SymlogDistribution MSE form
    (area report 02 measured the ratio at 0.500000). Fed identical
    symlog-space residuals (recon = symexp(pred)), the faithful form must be
        new = -SymlogDistribution(pred, dims=1).log_prob(target)
            = sum((pred - symlog(target))^2)  == 2 * old.

    Guards re-introduction of the 1/2.
    """
    from src.algorithms.dreamer_srl.loss import SymlogDistribution
    from src.algorithms.dreamer_srl.utils import symlog

    rng = np.random.default_rng(0xD3EAF + 1)
    T, B, D = 5, 4, 8
    pred = jnp.asarray(rng.standard_normal((T, B, D)), dtype=jnp.float32)
    target = jnp.asarray(rng.standard_normal((T, B, D)) * 3.0, dtype=jnp.float32)
    # No sub-tol residuals in this fixture (generic gaussian draws) — the tol
    # clamp must not fire, so the ratio is exactly 2.

    old = np.asarray(0.5 * jnp.sum((pred - symlog(target)) ** 2, axis=-1))  # [T, B]
    new = -np.asarray(SymlogDistribution(pred, dims=1).log_prob(target))    # [T, B]

    ratio = new / old
    np.testing.assert_allclose(ratio, 2.0, rtol=1e-5, err_msg=(
        "new/old obs-loss ratio != 2.0: the 0.5 inline factor (WP-SRL P3, "
        "the 2x recon under-weighting) has been re-introduced or the "
        "SymlogDistribution formula drifted."
    ))


def test_reconstruction_loss_with_symlog_po():
    """reconstruction_loss end-to-end with po={'obs': SymlogDistribution(...)}.

    Extends existing coverage to the newly-live call path (train.py routes
    the WM loss through the faithful reconstruction_loss after WP-SRL P3):
    total == mean of the manually assembled four-term sum, and the returned
    obs term == mean of -po['obs'].log_prob(obs).
    """
    from src.algorithms.dreamer_srl.loss import (
        IndependentBernoulli,
        SymlogDistribution,
        reconstruction_loss,
    )

    rng = np.random.default_rng(0xD3EAF + 2)
    T, B, D = 4, 3, 6
    S, C = 4, 8  # categoricals x classes
    kl_dynamic, kl_representation = 0.5, 0.1
    kl_free_nats, kl_regularizer = 1.0, 1.0
    continue_scale_factor = 1.0

    obs = jnp.asarray(rng.standard_normal((T, B, D)) * 2.0, dtype=jnp.float32)
    obs_pred = jnp.asarray(rng.standard_normal((T, B, D)), dtype=jnp.float32)
    reward_logits = jnp.asarray(rng.standard_normal((T, B, 255)), dtype=jnp.float32)
    rewards = jnp.asarray(rng.standard_normal((T, B, 1)), dtype=jnp.float32)
    cont_logits = jnp.asarray(rng.standard_normal((T, B, 1)), dtype=jnp.float32)
    cont_targets = jnp.asarray(
        rng.integers(0, 2, (T, B, 1)).astype(np.float32), dtype=jnp.float32
    )
    prior_logits = jnp.asarray(rng.standard_normal((T, B, S, C)), dtype=jnp.float32)
    post_logits = jnp.asarray(rng.standard_normal((T, B, S, C)), dtype=jnp.float32)

    po = {"obs": SymlogDistribution(obs_pred, dims=1)}
    pr = TwoHotEncoding(reward_logits, dims=1)
    pc = IndependentBernoulli(cont_logits)

    total, kl_mean, kl_loss_mean, rew_mean, obs_mean, cont_mean = reconstruction_loss(
        po, {"obs": obs}, pr, rewards,
        prior_logits, post_logits,
        kl_dynamic=kl_dynamic, kl_representation=kl_representation,
        kl_free_nats=kl_free_nats, kl_regularizer=kl_regularizer,
        pc=pc, continue_targets=cont_targets,
        continue_scale_factor=continue_scale_factor,
    )

    # Manual four-term assembly (sheeprl loss.py:9-88 semantics).
    obs_l = -np.asarray(po["obs"].log_prob(obs))                    # [T, B]
    rew_l = -np.asarray(pr.log_prob(rewards))                       # [T, B]
    cont_l = continue_scale_factor * (-np.asarray(pc.log_prob(cont_targets)))  # [T, B]
    lp = np.asarray(jax.nn.log_softmax(post_logits, axis=-1))
    lq = np.asarray(jax.nn.log_softmax(prior_logits, axis=-1))
    kl = (np.exp(lp) * (lp - lq)).sum(axis=-1).sum(axis=-1)         # [T, B]
    kl_l = (kl_dynamic * np.maximum(kl, kl_free_nats)
            + kl_representation * np.maximum(kl, kl_free_nats))     # [T, B]
    want_total = (kl_regularizer * kl_l + obs_l + rew_l + cont_l).mean()

    assert abs(float(total) - float(want_total)) < 1e-4, (
        f"reconstruction_loss total {float(total):.6f} != manual four-term "
        f"sum {float(want_total):.6f}"
    )
    assert abs(float(obs_mean) - float(obs_l.mean())) < 1e-5, (
        f"returned obs term {float(obs_mean):.6f} != mean(-po.log_prob) "
        f"{float(obs_l.mean()):.6f}"
    )
    assert abs(float(kl_mean) - float(kl.mean())) < 1e-5
    assert abs(float(kl_loss_mean) - float(kl_l.mean())) < 1e-5
    assert abs(float(rew_mean) - float(rew_l.mean())) < 1e-5
    assert abs(float(cont_mean) - float(cont_l.mean())) < 1e-5


# ---------------------------------------------------------------------------
# D-017 — configurable two-hot bin range (algo.twohot_low / algo.twohot_high)
#
# The class default stays low=-20, high=20 (sheeprl parity — pinned by the
# test_twohot_* bit-identity tests above). These tests cover the NON-default
# range path used by the bins-resolution experiment (±6).
# ---------------------------------------------------------------------------

def test_twohot_custom_range_bins_linspace():
    """Custom low/high produce bins = linspace(low, high, 255) in symlog space.

    D-017: the bin range is configurable per instantiation site (train.py
    threads algo.twohot_low/high); the grid must be a plain linspace over the
    requested range — still in SYMLOG space, never symexp'd at storage.
    """
    dummy_logits = jnp.zeros((1, 255))
    dist = TwoHotEncoding(dummy_logits, dims=0, low=-6.0, high=6.0)

    expected = jnp.linspace(-6.0, 6.0, 255)
    assert dist.bins.shape == (255,)
    assert float(dist.bins[0]) == -6.0, f"bins[0]={float(dist.bins[0])}, expected -6.0"
    assert float(dist.bins[254]) == 6.0, f"bins[254]={float(dist.bins[254])}, expected +6.0"
    max_abs_diff = float(jnp.max(jnp.abs(dist.bins - expected)))
    assert max_abs_diff == 0.0, (
        f"custom-range bins differ from linspace(-6, 6, 255): "
        f"max_abs_diff={max_abs_diff:.3e}"
    )
    # Guard against symexp-at-storage on the custom range (historical-bug class):
    # symexp(-6) ≈ -402.4, not -6.0.
    assert abs(float(dist.bins[0]) - (-6.0)) < 1e-6


@pytest.mark.parametrize("target", [-100.0, -22.0, 0.0])
def test_twohot_pm6_round_trip(target):
    """Two-hot encode → decode round-trip at range ±6 recovers the target.

    D-017: |symlog(-100)| ≈ 4.62 and |symlog(-22)| ≈ 3.14 — both inside the ±6
    symlog-space grid, so the ±6 range must represent them without clipping.
    Encode the target into its two-hot weight vector (same arithmetic as
    log_prob), feed log(weights) back in as logits (softmax recovers the
    two-hot distribution), and check that .mean decodes back to the original
    value within one symlog-space bin width (12 / 254 ≈ 0.0472).
    """
    from src.algorithms.dreamer_srl.utils import symlog as _symlog

    low, high = -6.0, 6.0
    n_bins = 255
    bin_width = (high - low) / (n_bins - 1)

    # Bin grid for the custom range
    bins = TwoHotEncoding(jnp.zeros((1, n_bins)), dims=1, low=low, high=high).bins

    # Two-hot encode the target (same code path as log_prob; see
    # test_twohot_encode_matches_sheeprl for the sheeprl-side derivation)
    x = _symlog(jnp.asarray([[target]]))  # [1, 1] symlog-space target
    below = (bins <= x).astype(jnp.int32).sum(axis=-1, keepdims=True) - 1
    above = jnp.minimum(below + 1, n_bins - 1)
    below = jnp.maximum(below, 0)
    equal = below == above
    dist_to_below = jnp.where(equal, jnp.ones_like(x), jnp.abs(bins[below] - x))
    dist_to_above = jnp.where(equal, jnp.ones_like(x), jnp.abs(bins[above] - x))
    total = dist_to_below + dist_to_above
    twohot = (
        jax.nn.one_hot(below, n_bins) * (dist_to_above / total)[..., None]
        + jax.nn.one_hot(above, n_bins) * (dist_to_below / total)[..., None]
    ).squeeze(-2)  # [1, 255]

    # Decode: log(weights) as logits → softmax recovers the two-hot weights
    dist = TwoHotEncoding(jnp.log(twohot + 1e-12), dims=1, low=low, high=high)
    decoded = float(dist.mean[0, 0])

    err_symlog = abs(float(_symlog(jnp.asarray(decoded))) - float(_symlog(jnp.asarray(target))))
    assert err_symlog < bin_width, (
        f"±6 round-trip failed for target={target}: decoded={decoded:.4f}, "
        f"symlog-space error {err_symlog:.5f} >= bin width {bin_width:.5f}"
    )
