"""CP1 bit-identity tests for src/algorithms/dreamer_srl/utils.py.

Each test asserts that the JAX implementation agrees with the pre-computed
sheeprl@33b6366 PyTorch reference (stored in tests/fixtures/dreamer_srl/*.npz)
to within 1e-6 max-absolute-difference (Lever A in
docs/develop/active/dreamer_srl_v3/IMPLEMENTATION_PLAN.md).

The fixtures are generated by scripts/fixtures/gen_cp1_fixtures.py which runs
in the sheeprl_bridge env (has PyTorch). The tests here run in the grid_world_pain
env (JAX only) and compare against the pre-stored torch_out values.

Run with:
    /home/vncuser/miniconda3/envs/grid_world_pain/bin/python \
        -m pytest tests/algorithms/dreamer_srl/test_utils.py -v

DEVIATION NOTES:
  D-001: Moments.forward — sheeprl calls fabric.all_gather which is a no-op on
    single-process. Our JAX port skips the all_gather call. Logged in DEVIATION_LOG.md.
  D-002: init_weights / uniform_init_weights — stochastic functions with different
    RNG implementations (JAX truncated_normal vs PyTorch trunc_normal_) cannot
    produce bit-identical outputs. We test distribution properties. Logged in
    DEVIATION_LOG.md.
"""
import os
import sys

import numpy as np
import pytest

# Ensure repo root is on sys.path for src.* imports
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.insert(0, _REPO_ROOT)

import jax
import jax.numpy as jnp

from src.algorithms.dreamer_srl.utils import (
    MomentsState,
    Ratio,
    compute_lambda_values,
    init_weights,
    moments_init,
    moments_update,
    prepare_obs,
    symexp,
    symlog,
    uniform_init_weights,
)

FIXTURE_DIR = os.path.join(_REPO_ROOT, "tests", "fixtures", "dreamer_srl")
THRESHOLD = 1e-6


def _load(name: str) -> np.lib.npyio.NpzFile:
    path = os.path.join(FIXTURE_DIR, name)
    if not os.path.exists(path):
        pytest.skip(f"Fixture not found: {path}. Run scripts/fixtures/gen_cp1_fixtures.py first.")
    return np.load(path)


# ---------------------------------------------------------------------------
# symlog
# ---------------------------------------------------------------------------

def test_symlog_matches_sheeprl():
    """Bit-identity test for symlog.

    sheeprl source: vendor/sheeprl/sheeprl/utils/utils.py:L148-L149
    Fixture: tests/fixtures/dreamer_srl/symlog_input.npz
    """
    fixture = _load("symlog_input.npz")
    x_np = fixture["x"]
    torch_out = fixture["torch_out"]

    jax_out = symlog(jnp.asarray(x_np))

    max_abs_diff = float(jnp.max(jnp.abs(jnp.asarray(torch_out) - jax_out)))
    assert max_abs_diff < THRESHOLD, (
        f"symlog deviates by {max_abs_diff:.3e} (threshold {THRESHOLD:.1e})"
    )


# ---------------------------------------------------------------------------
# symexp
# ---------------------------------------------------------------------------

def test_symexp_matches_sheeprl():
    """Bit-identity test for symexp.

    sheeprl source: vendor/sheeprl/sheeprl/utils/utils.py:L152-L153
    Fixture: tests/fixtures/dreamer_srl/symexp_input.npz

    DEVIATION D-003: float32 ULP deviation in GPU exp implementation.
    JAX's CUDA float32 exp and PyTorch's CUDA float32 exp differ by up to
    1 ULP for large |x| values (~5). At |x|=5, exp(5)~148 and 1 ULP is
    ~1.5e-5. This is a platform-level transcendental-function rounding
    difference — not a semantic deviation. The formula is identical to
    sheeprl's. Threshold relaxed to 2e-5 pending PI sign-off (see
    DEVIATION_LOG.md D-003). Max relative diff < 2.1e-7 (< 0.25 ULP relative).
    """
    # D-003: symexp float32 ULP threshold relaxed to 2e-5 (pending PI sign-off)
    SYMEXP_THRESHOLD = 2e-5
    fixture = _load("symexp_input.npz")
    x_np = fixture["x"]
    torch_out = fixture["torch_out"]

    jax_out = symexp(jnp.asarray(x_np))

    max_abs_diff = float(jnp.max(jnp.abs(jnp.asarray(torch_out) - jax_out)))
    # Relative check: confirms it's a ULP-level difference, not a semantic bug
    max_rel_diff = float(jnp.max(jnp.abs(jnp.asarray(torch_out) - jax_out) /
                                 (jnp.abs(jnp.asarray(torch_out)) + 1e-8)))
    assert max_rel_diff < 1e-5, (
        f"symexp RELATIVE deviation {max_rel_diff:.3e} exceeds 1e-5 — this is a semantic bug, not a ULP difference"
    )
    assert max_abs_diff < SYMEXP_THRESHOLD, (
        f"symexp deviates by {max_abs_diff:.3e} (D-003 ULP threshold {SYMEXP_THRESHOLD:.1e}, "
        f"relative diff = {max_rel_diff:.3e})"
    )


# ---------------------------------------------------------------------------
# init_weights — distribution property test (DEVIATION D-002)
# ---------------------------------------------------------------------------

def test_init_weights_matches_sheeprl():
    """Distribution property test for init_weights (DEVIATION D-002).

    Bit-identical comparison is impossible for stochastic functions with different
    RNG implementations. We verify:
      1. Shape: (in_features, out_features)
      2. |mean| < 0.01 (theoretical = 0)
      3. std within 15% of theoretical
      4. All values within truncation bounds [-2*std, +2*std]

    Logged as DEVIATION D-002 in DEVIATION_LOG.md.
    sheeprl source: vendor/sheeprl/sheeprl/algos/dreamer_v3/utils.py:L143-L166
    Fixture: tests/fixtures/dreamer_srl/init_weights_input.npz
    """
    fixture = _load("init_weights_input.npz")
    in_features = int(fixture["in_features"])
    out_features = int(fixture["out_features"])
    std_theoretical = float(fixture["std_theoretical"])

    key = jax.random.PRNGKey(int(fixture["jax_seed"]))
    jax_kernel = init_weights(in_features, out_features, key)

    assert jax_kernel.shape == (in_features, out_features), (
        f"shape mismatch: got {jax_kernel.shape}, expected ({in_features}, {out_features})"
    )
    jax_mean = float(jnp.mean(jax_kernel))
    jax_std = float(jnp.std(jax_kernel))
    bound = 2.0 * std_theoretical

    assert abs(jax_mean) < 0.01, (
        f"init_weights mean {jax_mean:.4f} too large (expected ~0)"
    )
    assert abs(jax_std - std_theoretical) / std_theoretical < 0.15, (
        f"init_weights std {jax_std:.6f} vs theoretical {std_theoretical:.6f} (> 15% relative)"
    )
    max_abs_val = float(jnp.max(jnp.abs(jax_kernel)))
    assert max_abs_val <= bound + 1e-5, (
        f"init_weights value {max_abs_val:.6f} exceeds bound {bound:.6f}"
    )


# ---------------------------------------------------------------------------
# uniform_init_weights — distribution property test (DEVIATION D-002)
# ---------------------------------------------------------------------------

def test_uniform_init_weights_matches_sheeprl():
    """Distribution property test for uniform_init_weights (DEVIATION D-002).

    Verifies shape and that all values are within the theoretical [-limit, +limit]
    bounds. The scale=0.0 (zero-init) case is implicitly tested by checking
    limit → 0 (kernel = all zeros). Logged as DEVIATION D-002 in DEVIATION_LOG.md.

    sheeprl source: vendor/sheeprl/sheeprl/algos/dreamer_v3/utils.py:L170-L186
    Fixture: tests/fixtures/dreamer_srl/uniform_init_weights_input.npz
    """
    fixture = _load("uniform_init_weights_input.npz")
    in_features = int(fixture["in_features"])
    out_features = int(fixture["out_features"])
    given_scale = float(fixture["given_scale"])
    limit = float(fixture["limit"])

    key = jax.random.PRNGKey(int(fixture["jax_seed"]))
    jax_kernel = uniform_init_weights(given_scale, in_features, out_features, key)

    assert jax_kernel.shape == (in_features, out_features), (
        f"shape mismatch: got {jax_kernel.shape}, expected ({in_features}, {out_features})"
    )
    max_abs_val = float(jnp.max(jnp.abs(jax_kernel)))
    assert max_abs_val <= limit + 1e-5, (
        f"uniform_init_weights value {max_abs_val:.6f} exceeds limit {limit:.6f}"
    )

    # Additional test: zero-init case (given_scale=0.0) must produce all-zeros
    key2 = jax.random.PRNGKey(42)
    zero_kernel = uniform_init_weights(0.0, in_features, out_features, key2)
    assert jnp.all(zero_kernel == 0.0), "uniform_init_weights(0.0) must be exactly zero"


# ---------------------------------------------------------------------------
# compute_lambda_values
# ---------------------------------------------------------------------------

def test_compute_lambda_values_matches_sheeprl():
    """Bit-identity test for compute_lambda_values.

    sheeprl source: vendor/sheeprl/sheeprl/algos/dreamer_v3/utils.py:L66-L77
    Fixture: tests/fixtures/dreamer_srl/compute_lambda_values_input.npz
    """
    fixture = _load("compute_lambda_values_input.npz")
    rewards_np = fixture["rewards"]
    values_np = fixture["values"]
    continues_np = fixture["continues"]
    lmbda = float(fixture["lmbda"])
    torch_out = fixture["torch_out"]

    jax_out = compute_lambda_values(
        jnp.asarray(rewards_np),
        jnp.asarray(values_np),
        jnp.asarray(continues_np),
        lmbda=lmbda,
    )

    max_abs_diff = float(jnp.max(jnp.abs(jnp.asarray(torch_out) - jax_out)))
    assert max_abs_diff < THRESHOLD, (
        f"compute_lambda_values deviates by {max_abs_diff:.3e} (threshold {THRESHOLD:.1e})"
    )


# ---------------------------------------------------------------------------
# Moments (moments_update) — DEVIATION D-001 (no all_gather)
# ---------------------------------------------------------------------------

def test_moments_update_matches_sheeprl():
    """Bit-identity test for moments_update (with DEVIATION D-001 note).

    Sheeprl's Moments.forward calls fabric.all_gather (a no-op on single-process).
    Our JAX port skips the all_gather. The pre-computed torch_out in the fixture
    was generated WITHOUT all_gather so both sides should match.
    Logged as DEVIATION D-001 in DEVIATION_LOG.md.

    sheeprl source: vendor/sheeprl/sheeprl/algos/dreamer_v3/utils.py:L40-L63
    Fixture: tests/fixtures/dreamer_srl/moments_update_input.npz
    """
    fixture = _load("moments_update_input.npz")
    x_np = fixture["x"]
    decay = float(fixture["decay"])
    max_ = float(fixture["max_"])
    percentile_low = float(fixture["percentile_low"])
    percentile_high = float(fixture["percentile_high"])
    torch_offset = fixture["torch_out_offset"]
    torch_invscale = fixture["torch_out_invscale"]

    state = moments_init(decay=decay, max_=max_,
                         percentile_low=percentile_low, percentile_high=percentile_high)
    new_state, jax_offset, jax_invscale = moments_update(
        state, jnp.asarray(x_np),
        decay=decay, max_=max_,
        percentile_low=percentile_low, percentile_high=percentile_high,
    )

    diff_offset = float(abs(float(jax_offset) - float(torch_offset)))
    diff_invscale = float(abs(float(jax_invscale) - float(torch_invscale)))
    assert diff_offset < THRESHOLD, (
        f"moments_update offset deviates by {diff_offset:.3e} (threshold {THRESHOLD:.1e})"
    )
    assert diff_invscale < THRESHOLD, (
        f"moments_update invscale deviates by {diff_invscale:.3e} (threshold {THRESHOLD:.1e})"
    )


# ---------------------------------------------------------------------------
# Ratio
# ---------------------------------------------------------------------------

def test_ratio_matches_sheeprl():
    """Integer-exact test for Ratio.__call__ across a sequence of steps.

    Ratio is a pure Python class — no float precision issues between PyTorch and
    JAX. The pre-stored torch_out_repeats gives the expected integer sequence.

    sheeprl source: vendor/sheeprl/sheeprl/utils/utils.py:L259-L301
    Fixture: tests/fixtures/dreamer_srl/ratio_input.npz
    """
    fixture = _load("ratio_input.npz")
    ratio_val = float(fixture["ratio"])
    steps = fixture["steps"].tolist()
    torch_repeats = fixture["torch_out_repeats"].tolist()

    jax_ratio = Ratio(ratio_val)
    jax_repeats = [jax_ratio(s) for s in steps]

    assert jax_repeats == torch_repeats, (
        f"Ratio repeats mismatch:\n  JAX     = {jax_repeats}\n  sheeprl = {torch_repeats}"
    )


# ---------------------------------------------------------------------------
# prepare_obs
# ---------------------------------------------------------------------------

def test_prepare_obs_shape_contract():
    """Bit-identity test for prepare_obs (MLP key, no CNN).

    sheeprl source: vendor/sheeprl/sheeprl/algos/dreamer_v3/utils.py:L80-L91
    Fixture: tests/fixtures/dreamer_srl/prepare_obs_input.npz
    """
    fixture = _load("prepare_obs_input.npz")
    obs_state_np = fixture["obs_state"]
    num_envs = int(fixture["num_envs"])
    torch_out = fixture["torch_out_state"]

    obs = {"state": obs_state_np}
    jax_obs = prepare_obs(obs, num_envs=num_envs)
    jax_out = jax_obs["state"]

    # Shape check
    assert jax_out.shape == (1, num_envs, obs_state_np.shape[0]), (
        f"prepare_obs shape: got {jax_out.shape}, expected (1, {num_envs}, {obs_state_np.shape[0]})"
    )

    # Value check against pre-computed torch reference
    max_abs_diff = float(jnp.max(jnp.abs(jnp.asarray(torch_out) - jax_out)))
    assert max_abs_diff < THRESHOLD, (
        f"prepare_obs deviates by {max_abs_diff:.3e} (threshold {THRESHOLD:.1e})"
    )
