"""CP8 — end-to-end forward parity merge-gate test.

CP8 is the INTEGRATION TEST for everything CP1-CP7 built. Unlike CP1-CP7,
which each carry per-function Lever-A bit-identity tests, CP8 has ONE test
that verifies the COMPOSITION of the complete training step.

Purpose: verify that all CP1-CP7 building blocks COMPOSE correctly —
i.e., the full pipeline (RSSM forward, §S5 splice, lambda values, discount,
actor objective, critic loss, Polyak update) executes without composition
bugs (wrong call-order, wrong tensor-slicing, missing §S rule).

The test runs `scripts/dreamer_srl_offline_check.py` and asserts exit 0.
The offline check script loads the CP8 fixture, reconstructs the pipeline
from fixture-stored intermediate tensors (to avoid PRNG non-determinism in
the stochastic RSSM rollout), and verifies 18 checks across Parts A-F.

CP8 forward-looking items from CP7 professor (all verified by offline check):
  1. sg(action) at actor forward pass — applied before log_prob upstream
  2. Polyak fires-before-train ordering — polyak_update importable from train.py
  3. §S5 splice fixture-visible test — continues_spliced[0] != continues_predicted[0]

Fixture:
    tests/fixtures/dreamer_srl/end_to_end_parity_input.npz
    Generated by: scripts/fixtures/gen_cp8_fixtures.py (grid_world_pain env)

Offline check:
    scripts/dreamer_srl_offline_check.py

Run with:
    /home/vncuser/miniconda3/envs/grid_world_pain/bin/python \\
        -m pytest tests/algorithms/dreamer_srl/test_end_to_end_parity.py -v

CHECKPOINT_REGISTRY["CP8"] = []  — NO per-function Lever-A entries.
"""
from __future__ import annotations

import os
import subprocess
import sys

import pytest


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
))))

OFFLINE_CHECK_SCRIPT = os.path.join(REPO_ROOT, "scripts", "dreamer", "dreamer_srl_offline_check.py")
FIXTURE_PATH = os.path.join(
    REPO_ROOT, "tests", "fixtures", "dreamer_srl", "end_to_end_parity_input.npz"
)
PYTHON = "/home/vncuser/miniconda3/envs/grid_world_pain/bin/python"


@pytest.mark.integration
def test_end_to_end_parity():
    """CP8 merge-gate: full training step composition verifies exit 0.

    Runs the offline check script and asserts it exits cleanly.
    The script checks 18 integration-level properties across:
      - Part A: World-model loss (predicted_rewards, predicted_values)
      - Part B: §S5 splice, lambda values, discount
      - Part C: Actor objective, advantage normalisation (§S7)
      - Part D: Critic loss, cascade fix #29 two-term guard
      - Part E: Polyak update, call-order, sg(advantage) source check
      - Part F: World-model scalar reward loss

    A non-zero exit code indicates an integration bug (wrong call-order,
    wrong tensor slicing, missing §S rule, or missing cascade fix).
    """
    if not os.path.exists(FIXTURE_PATH):
        pytest.skip(
            f"CP8 fixture missing: {FIXTURE_PATH}\n"
            f"Generate with: {PYTHON} scripts/fixtures/gen_cp8_fixtures.py"
        )

    result = subprocess.run(
        [PYTHON, OFFLINE_CHECK_SCRIPT],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )

    # Print output regardless of outcome so pytest -v shows the check details
    print("\n--- dreamer_srl_offline_check.py output ---")
    print(result.stdout)
    if result.stderr:
        print("--- stderr ---")
        print(result.stderr)
    print("--- end ---")

    assert result.returncode == 0, (
        f"CP8 offline check FAILED (exit {result.returncode}).\n"
        f"See output above for which of the 18 checks failed and why.\n"
        f"Re-run manually: {PYTHON} {OFFLINE_CHECK_SCRIPT}"
    )
