"""Tests for the modulation-site refactor — uniform FiLM at selectable sites.

Plain-language context: the agent carries a small second network (the
"neuromodulator") that continuously re-tunes the main policy network. It used to
do that through four different mechanisms at four different places. This refactor
makes every place use the SAME operation — multiply each neuron by a learned gain
and add a learned offset, the technique called FiLM — and makes each place
switchable from the config file (`modulation.sites.{encoder,rnn,actor,critic}`).

The two promises these tests defend:
  1. The UNMODULATED baseline is bit-identical to what it was before the
     refactor. It is the project's control condition; if it drifts, every past
     comparison silently becomes invalid.
  2. A config that asks for the OLD arrangement (encoder + task-GRU gate bias +
     temperature) gets the OLD network back, byte for byte — same parameters,
     same forward pass — so existing checkpoints still restore.

Both are pinned against `.npz` "golden fixtures" captured on the pre-refactor
code (tests/fixtures/modulation/, generated by generate_golden.py). The fixtures
come in two flavours because real runs and the fast smoke case differ: a small
"flat" encoder with no LayerNorm, and the hierarchical per-sensor encoder with
LayerNorm that every real recurrent_ppo_nmn_* config actually uses.

Plan: docs/develop/active/neuromodulation/MODULATION_SITE_REFACTOR.md
"""
import importlib.util
import itertools
import os
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

import jax
jax.config.update("jax_platform_name", "cpu")

import jax.numpy as jnp
import numpy as np
import optax
import pytest
from flax import nnx

from src.models.recurrent_ppo_network import ActorCriticRNN

_GEN_PATH = os.path.join(_REPO, "tests", "fixtures", "modulation", "generate_golden.py")
_spec = importlib.util.spec_from_file_location("_modulation_golden", _GEN_PATH)
golden = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(golden)

FIXTURE_DIR = os.path.dirname(_GEN_PATH)
MODES = ["flat", "hier_ln"]


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def _mod_cfg(*, encoder=True, rnn=True, actor=False, critic=False,
             mechanism="gate_bias", temperature=True, clip=(0.5, 3.0), **over):
    cfg = {
        "type": "FiLM",
        "mod_hidden_size": 8,
        "grouping_size": 1,
        "percept_bias_init": 1.0,
        "percept_add_bias_init": 0.0,
        "memory_bias_init": 0.0,
        "memory_clip": [-2.0, 2.0],
        "sites": {"encoder": encoder, "rnn": rnn, "actor": actor, "critic": critic},
        "rnn_mechanism": mechanism,
        "temperature": ({"enabled": True, "clip": list(clip)} if temperature
                        else {"enabled": False}),
    }
    cfg.update(over)
    return cfg


def _build(mode="flat", modulation_config=None, seed=golden.SEED):
    spec = golden.SPECS[mode]
    return ActorCriticRNN(
        input_dim=spec["input_dim"],
        action_dim=spec["action_dim"],
        hidden_size=spec["hidden_size"],
        rngs=nnx.Rngs(seed),
        rnn_type="GRU",
        activation="tanh",
        modulation_config=modulation_config,
        observation_breakdown=spec["breakdown"],
        encoding_config=spec["encoding_config"],
    )


def _fixture(name):
    return np.load(os.path.join(FIXTURE_DIR, name))


def _assert_matches(ref, data, prefix):
    keys = [k for k in ref.files if k.startswith(prefix)]
    assert keys, f"fixture has no {prefix}* entries"
    assert set(keys) == {k for k in data if k.startswith(prefix)}, (
        f"{prefix} key set differs from the pre-change fixture: "
        f"{sorted(set(keys) ^ {k for k in data if k.startswith(prefix)})}"
    )
    for k in keys:
        assert np.array_equal(ref[k], data[k]), f"{k} is not bit-identical"


# --------------------------------------------------------------------------
# V1 / V2 — bit-identity against pre-change golden fixtures
# --------------------------------------------------------------------------

@pytest.mark.parametrize("mode", MODES)
def test_baseline_forward_matches_golden(mode):
    """The unmodulated network's forward pass must be bit-identical to the
    pre-refactor code. This is the project's control condition."""
    data = golden.snapshot(mode, modulated=False)
    _assert_matches(_fixture(f"{mode}_baseline.npz"), data, "out/")


@pytest.mark.parametrize("mode", MODES)
def test_baseline_param_tree_matches_golden(mode):
    """Same for the unmodulated parameter tree: identical key set, shapes AND
    values from a fixed seed (a reordered layer would shift the RNG stream)."""
    data = golden.snapshot(mode, modulated=False)
    _assert_matches(_fixture(f"{mode}_baseline.npz"), data, "param/")


@pytest.mark.parametrize("mode", MODES)
def test_legacy_equivalent_forward_matches_golden(mode):
    """sites={encoder,rnn} + rnn_mechanism='gate_bias' + temperature on must
    reproduce the pre-refactor MODULATED forward pass bitwise."""
    data = golden.snapshot(mode, modulated=True)
    _assert_matches(_fixture(f"{mode}_legacy.npz"), data, "out/")


@pytest.mark.parametrize("mode", MODES)
def test_legacy_equivalent_param_tree_matches_golden(mode):
    """Same for the parameter tree — this is what makes existing neuromodulation
    checkpoints still restorable."""
    data = golden.snapshot(mode, modulated=True)
    _assert_matches(_fixture(f"{mode}_legacy.npz"), data, "param/")


# --------------------------------------------------------------------------
# Site toggling — which heads exist
# --------------------------------------------------------------------------

_SITE_NAMES = ("encoder", "rnn", "actor", "critic")
_SUBSETS = [s for n in range(1, 5) for s in itertools.combinations(_SITE_NAMES, n)]


@pytest.mark.parametrize("mechanism", ["activation", "gate_bias"])
@pytest.mark.parametrize("subset", _SUBSETS, ids=["+".join(s) for s in _SUBSETS])
def test_site_toggles_build_expected_heads(subset, mechanism):
    """For every non-empty combination of sites x mechanism, exactly the expected
    modulator heads and baselines exist — no more, no fewer. A head that exists
    but is never read is dead weight receiving no gradient (the failure mode of
    the fixed LSTM/z_memory bug)."""
    on = {name: (name in subset) for name in _SITE_NAMES}
    model = _build("flat", _mod_cfg(mechanism=mechanism, temperature=False, **on))
    mod = model.modulator

    expected = set()
    if on["encoder"]:
        expected |= {"head_unimodal", "head_unimodal_add", "head_multimodal",
                     "head_multimodal_add", "z_unimodal_baseline", "z_hidden_baseline",
                     "z_unimodal_add_baseline", "z_hidden_add_baseline"}
    if on["rnn"] and mechanism == "gate_bias":
        expected |= {"head_memory", "z_mem_baseline"}
    if on["rnn"] and mechanism == "activation":
        expected |= {"head_rnn", "head_rnn_add", "z_rnn_baseline", "z_rnn_add_baseline"}
    if on["actor"]:
        expected |= {"head_actor", "head_actor_add", "z_actor_baseline", "z_actor_add_baseline"}
    if on["critic"]:
        expected |= {"head_critic", "head_critic_add", "z_critic_baseline", "z_critic_add_baseline"}
    # temperature is off in this parametrisation
    assert not hasattr(mod, "head_action")

    present = {a for a in dir(mod)
               if (a.startswith("head_") or a.endswith("_baseline"))}
    assert present == expected, f"unexpected: {present - expected}, missing: {expected - present}"


def test_plain_gru_cell_used_when_not_gate_bias():
    """D6 — the hand-built ModulatedGRUCell has a different initialisation scheme
    and gate polarity from the plain nnx.GRUCell, so using it whenever modulation
    is on imports an initialisation confound into every comparison. It must now
    be built ONLY for the gate-bias mechanism."""
    from src.models.modulated_gru_cell import ModulatedGRUCell

    m_gate = _build("flat", _mod_cfg(mechanism="gate_bias"))
    assert isinstance(m_gate.rnn_cell, ModulatedGRUCell)

    for cfg in (_mod_cfg(mechanism="activation"),
                _mod_cfg(rnn=False, encoder=True),
                _mod_cfg(rnn=False, encoder=False, actor=True),
                _mod_cfg(rnn=False, encoder=False, critic=True)):
        model = _build("flat", cfg)
        assert not isinstance(model.rnn_cell, ModulatedGRUCell)
        assert isinstance(model.rnn_cell, nnx.GRUCell)


# --------------------------------------------------------------------------
# Strict-config contract (no fallback defaults)
# --------------------------------------------------------------------------

def test_legacy_temp_clip_key_raises():
    """D9 — a config still carrying the flat `temp_clip` key must fail loudly.
    The message must ALSO tell someone re-analysing an archived run that
    RE-TRAINING, not re-evaluation, is the remedy (D16), so a future message edit
    cannot quietly strip that guidance."""
    cfg = _mod_cfg()
    cfg["temp_clip"] = [0.5, 3.0]
    with pytest.raises(ValueError) as exc:
        _build("flat", cfg)
    msg = str(exc.value)
    assert "temp_clip" in msg and "temperature" in msg
    assert "RE-TRAIN" in msg.upper()
    assert "ARCHIVED" in msg.upper()


def test_all_sites_off_and_temperature_off_raises():
    """D13 — a modulator with nothing to write to would run every step and
    receive no gradient: dead weight with no error."""
    cfg = _mod_cfg(encoder=False, rnn=False, actor=False, critic=False, temperature=False)
    with pytest.raises(ValueError, match="every site is disabled"):
        _build("flat", cfg)


@pytest.mark.parametrize("site", _SITE_NAMES)
def test_missing_site_key_raises(site):
    """No-fallback-defaults contract, one case per site key."""
    cfg = _mod_cfg()
    del cfg["sites"][site]
    with pytest.raises(ValueError, match=f"sites.{site}"):
        _build("flat", cfg)


def test_missing_rnn_mechanism_raises():
    cfg = _mod_cfg()
    del cfg["rnn_mechanism"]
    with pytest.raises(ValueError, match="rnn_mechanism"):
        _build("flat", cfg)


def test_missing_temperature_enabled_raises():
    cfg = _mod_cfg()
    cfg["temperature"] = {}
    with pytest.raises(ValueError, match="enabled"):
        _build("flat", cfg)


def test_missing_temperature_clip_raises_when_enabled():
    cfg = _mod_cfg()
    cfg["temperature"] = {"enabled": True}
    with pytest.raises(ValueError, match="clip"):
        _build("flat", cfg)


def test_unknown_rnn_mechanism_raises():
    """D12 — do not repeat the config-boundary trap where an unknown
    `modulation.type` string silently built a Multiplicative modulator."""
    with pytest.raises(ValueError, match="rnn_mechanism"):
        _build("flat", _mod_cfg(mechanism="film"))


# --------------------------------------------------------------------------
# Behavioural contracts for the individual sites
# --------------------------------------------------------------------------

def test_temperature_disabled_leaves_logits_untouched():
    """With temperature off, the head must not exist and the logits must be the
    un-divided ones. Built with the same seed and the same enabled sites, the two
    models share every other parameter."""
    spec = golden.SPECS["flat"]
    obs = golden.fixed_observation(spec)

    m_off = _build("flat", _mod_cfg(temperature=False))
    m_on = _build("flat", _mod_cfg(temperature=True, clip=(0.5, 3.0)))
    assert not hasattr(m_off.modulator, "head_action")
    assert hasattr(m_on.modulator, "head_action")

    logits_off, _, _, info_off = m_off(obs, m_off.initial_state())
    logits_on, _, _, info_on = m_on(obs, m_on.initial_state())
    assert info_off.temperature is None
    assert info_on.temperature is not None
    # head_action is constructed LAST among the legacy heads, so both models share
    # every parameter that feeds the task path -> the only difference is the divide.
    np.testing.assert_allclose(np.asarray(logits_on),
                               np.asarray(logits_off) / np.asarray(info_on.temperature),
                               rtol=1e-6, atol=1e-6)


def test_rnn_activation_does_not_modulate_carry():
    """D5 — the 'activation' mechanism modulates the GRU's EMITTED output only.
    Scaling the carry state that is handed to the next timestep would re-create
    the double-gating pathology the gate-bias mechanism was invented to avoid.

    Deliberately non-identity gains: the modulator's gamma head bias is pushed to
    2.0 and its beta head bias to 1.0, so if the carry were being modulated the
    difference would be large and obvious.
    """
    spec = golden.SPECS["flat"]
    obs = golden.fixed_observation(spec)

    model = _build("flat", _mod_cfg(mechanism="activation", encoder=False,
                                    rnn=True, temperature=False))
    model.modulator.head_rnn.bias.value = jnp.full_like(model.modulator.head_rnn.bias.value, 2.0)
    model.modulator.head_rnn_add.bias.value = jnp.full_like(
        model.modulator.head_rnn_add.bias.value, 1.0)

    task_h, mod_h = model.initial_state()
    x = jnp.sign(obs) * jnp.log(jnp.abs(obs) + 1.0)
    x_proj = model.obs_encoder(x, flat_ln=getattr(model, 'mod_flat_ln', None))
    expected_carry, expected_xh = model.rnn_cell(task_h, x_proj)

    logits, value, (h_new, _), mod_info = model(obs, (task_h, mod_h))

    # The carry is untouched...
    np.testing.assert_array_equal(np.asarray(h_new), np.asarray(expected_carry))
    # ...while the emitted signal really was modulated (so the test is not vacuous).
    modulated_xh = mod_info.z_rnn * expected_xh + mod_info.z_rnn_add
    assert not np.allclose(np.asarray(modulated_xh), np.asarray(expected_xh))
    expected_logits = model.actor_fc2(model._activate(model.actor_fc1(modulated_xh)))
    np.testing.assert_allclose(np.asarray(logits), np.asarray(expected_logits),
                               rtol=1e-6, atol=1e-6)


@pytest.mark.parametrize("site", ["actor", "critic", "rnn"])
def test_new_site_changes_output_and_receives_gradient(site):
    """V5 — each new site must actually do something: perturbing its gain head
    changes the model's output, and one PPO-style update gives that head a
    non-zero gradient. A head that is constructed but never read would pass
    neither check."""
    spec = golden.SPECS["flat"]
    obs = golden.fixed_observation(spec)
    on = {"encoder": False, "rnn": False, "actor": False, "critic": False}
    on[site] = True
    model = _build("flat", _mod_cfg(mechanism="activation", temperature=False, **on))

    head = getattr(model.modulator, f"head_{site}")
    h0 = model.initial_state()
    before = model(obs, h0)
    head.bias.value = head.bias.value + 0.5
    after = model(obs, h0)

    changed = (not np.allclose(np.asarray(before[0]), np.asarray(after[0]))
               or not np.allclose(np.asarray(before[1]), np.asarray(after[1])))
    assert changed, f"site '{site}' is constructed but does not affect the output"

    def loss_fn(m):
        logits, value, _, _ = m(obs, h0)
        return jnp.sum(logits ** 2) + jnp.sum(value ** 2)

    grads = nnx.grad(loss_fn)(model)
    gpath = grads["modulator"][f"head_{site}"]["kernel"]
    gval = gpath.value if hasattr(gpath, "value") else gpath
    assert float(optax.global_norm(gval)) > 0.0, (
        f"site '{site}' head received a zero gradient"
    )


def test_disabled_site_is_really_bypassed():
    """V6 — with sites.actor off, the head must be absent AND the forward pass
    must equal the model with the actor path taken plainly."""
    spec = golden.SPECS["flat"]
    obs = golden.fixed_observation(spec)
    model = _build("flat", _mod_cfg(actor=False, mechanism="activation",
                                    rnn=False, temperature=False))
    assert not hasattr(model.modulator, "head_actor")

    logits, value, _, info = model(obs, model.initial_state())
    assert info.z_actor is None and info.z_actor_add is None
    assert info.z_critic is None and info.z_memory is None and info.z_rnn is None

    x = jnp.sign(obs) * jnp.log(jnp.abs(obs) + 1.0)
    task_h, mod_h = model.initial_state()
    mod_out, _ = model.modulator(x, mod_h)
    x_proj = model.obs_encoder.forward_with_modulation(
        x, mod_out, "FiLM", flat_ln=getattr(model, 'mod_flat_ln', None))
    _, x_h = model.rnn_cell(task_h, x_proj)
    expected = model.actor_fc2(model._activate(model.actor_fc1(x_h)))
    np.testing.assert_allclose(np.asarray(logits), np.asarray(expected),
                               rtol=1e-6, atol=1e-6)


# --------------------------------------------------------------------------
# JAX structure / staticness
# --------------------------------------------------------------------------

@pytest.mark.parametrize("subset", _SUBSETS, ids=["+".join(s) for s in _SUBSETS])
def test_initial_state_structure_invariant_across_sites(subset):
    """The hidden-state pytree must be (task_h, mod_h) whenever modulation is on,
    regardless of which sites are enabled — the modulator GRU always runs, so
    `mod_h` must never become conditional."""
    on = {name: (name in subset) for name in _SITE_NAMES}
    model = _build("flat", _mod_cfg(temperature=False, **on))
    ref = _build("flat", _mod_cfg())
    assert (jax.tree_util.tree_structure(model.initial_state(4))
            == jax.tree_util.tree_structure(ref.initial_state(4)))


def test_no_retrace_across_steps():
    """V8 — the site enables and the mechanism selector are plain Python
    attributes, so they belong to the static half of the jit cache key. Stepping
    the model repeatedly must compile exactly once."""
    traces = []
    model = _build("flat", _mod_cfg(encoder=True, rnn=True, actor=True, critic=True,
                                    mechanism="activation", temperature=True))
    spec = golden.SPECS["flat"]
    obs = golden.fixed_observation(spec)

    @nnx.jit
    def step(m, x, h):
        traces.append(1)          # executed at TRACE time only
        return m(x, h)

    h = model.initial_state()
    for _ in range(5):
        logits, value, h, _ = step(model, obs, h)
    jax.block_until_ready(logits)
    assert len(traces) == 1, f"model retraced {len(traces)} times"
