#!/usr/bin/env python3
"""Regenerate every docs/llm_wiki/entries/<topic>/_topic_index.md from entry frontmatter.

Topic indexes are GENERATED artifacts, not hand-maintained files. Two reasons:

1. Scale (LLM Wiki v2 critique): hand-written rows drift toward the full `summary`
   (~600 bytes each), and a scan-level index needs ~120. This generator renders the
   `headline:` field when present and otherwise truncates `summary` at the first
   sentence, capped at MAX_SUMMARY chars.
2. Races: two parallel sessions hand-editing the same index leave rows missing and
   counts stale (observed 2026-07-28). A generated index is race-proof — whoever
   runs last is correct.

Lifecycle markers ([superseded], [expired ...]) are rendered inline so staleness is
visible while scanning, instead of only after opening the entry.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ROOT = ROOT / "docs" / "llm_wiki"

MAX_SUMMARY = 140
ENTRY_RE = re.compile(r"^\d{8}_\d{4}_[a-z0-9_]+\.md$")

HEADER = """# _topic_index.md — `{folder}` folder

> One-line entry per insight, reverse-chronological (newest at top).
> Read this file when the user's question narrows to the `{folder}` topic.
> **Auto-generated by `scripts/claude/regen_wiki_indexes.py` — do not hand-edit.**
> To improve a row, set a `headline:` field on the entry itself.

**Folder definition**: {definition}
**Insights**: {count}
**Last updated**: {last_updated}
{state_line}
---

## Insights (newest first)

| Date | Time | ID | Summary |
|---|---|---|---|
"""


def _frontmatter(text: str) -> dict[str, str]:
    """Parse the simple one-key-per-line frontmatter these entries use."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    fm: dict[str, str] = {}
    for line in text[4:end].splitlines():
        m = re.match(r"^([a-z_]+):[ \t]*(.*)$", line)
        if m:
            fm[m.group(1)] = m.group(2).strip()
    return fm


def _unquote(v: str) -> str:
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        v = v[1:-1]
    return v.strip()


def _short(fm: dict[str, str]) -> str:
    """Row text: explicit headline wins; else first sentence of summary, capped."""
    head = _unquote(fm.get("headline", ""))
    if head:
        text = head
    else:
        text = _unquote(fm.get("summary", ""))
        # First sentence: a period followed by space+capital, or end of string.
        m = re.search(r"\.(?=\s+[A-Z(])", text)
        if m:
            text = text[: m.start() + 1]
    text = " ".join(text.split())
    if len(text) > MAX_SUMMARY:
        text = text[: MAX_SUMMARY - 1].rstrip() + "…"
    # Pipes would break the markdown table.
    return text.replace("|", "\\|")


def _markers(fm: dict[str, str], today: str) -> str:
    out = []
    if _unquote(fm.get("status", "")) == "superseded":
        out.append("**[superseded]**")
    vu = _unquote(fm.get("valid_until", ""))
    if vu and vu != "null" and vu < today:
        out.append(f"**[expired {vu}]**")
    return (" ".join(out) + " ") if out else ""


def _definition(index_path: Path, folder: str, root_index: str) -> str:
    """Preserve the existing folder definition; fall back to the ROOT_INDEX row."""
    if index_path.exists():
        m = re.search(r"^\*\*Folder definition\*\*:[ \t]*(.+)$", index_path.read_text(encoding="utf-8"), re.M)
        if m:
            return m.group(1).strip()
    m = re.search(rf"^\| `{re.escape(folder)}` \| ([^|]+) \|", root_index, re.M)
    return m.group(1).strip() if m else "(definition missing — add a row in ROOT_INDEX.md)"


def regen_folder(folder_dir: Path, root_index: str, today: str, dry_run: bool) -> tuple[bool, int]:
    entries = []
    for p in sorted(folder_dir.iterdir()):
        if not ENTRY_RE.match(p.name):
            continue
        fm = _frontmatter(p.read_text(encoding="utf-8"))
        if not fm:
            print(f"warn: {p.name} has no parsable frontmatter — skipped", file=sys.stderr)
            continue
        entries.append((_unquote(fm.get("date", "")), _unquote(fm.get("time", "")), p.stem, fm))

    entries.sort(key=lambda e: (e[0], e[1]), reverse=True)

    index_path = folder_dir / "_topic_index.md"
    state_line = "**Current belief**: [`_state.md`](_state.md)\n" if (folder_dir / "_state.md").exists() else ""
    out = HEADER.format(
        folder=folder_dir.name,
        definition=_definition(index_path, folder_dir.name, root_index),
        count=len(entries),
        last_updated=entries[0][0] if entries else "(empty)",
        state_line=state_line,
    )
    for date, time, stem, fm in entries:
        out += f"| {date} | {time} | [{stem}]({stem}.md) | {_markers(fm, today)}{_short(fm)} |\n"

    changed = (not index_path.exists()) or index_path.read_text(encoding="utf-8") != out
    if changed and not dry_run:
        index_path.write_text(out, encoding="utf-8")
    return changed, len(entries)


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate all wiki topic indexes from entry frontmatter.")
    ap.add_argument("--check", action="store_true", help="Read-only; exit 1 if any index would change.")
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="Root of the LLM Wiki (default: docs/llm_wiki).")
    args = ap.parse_args()

    entries_dir = args.root / "entries"
    if not entries_dir.is_dir():
        print(f"No entries/ directory under {args.root}", file=sys.stderr)
        return 1

    root_index_path = args.root / "ROOT_INDEX.md"
    root_index = root_index_path.read_text(encoding="utf-8") if root_index_path.exists() else ""
    today = _dt.date.today().isoformat()

    changed_total = 0
    for folder_dir in sorted(d for d in entries_dir.iterdir() if d.is_dir()):
        changed, n = regen_folder(folder_dir, root_index, today, dry_run=args.check)
        flag = "would change" if (changed and args.check) else ("updated" if changed else "unchanged")
        print(f"  {folder_dir.name:<24} {n:>3} entries  {flag}")
        changed_total += int(changed)

    if args.check:
        if changed_total:
            print(f"{changed_total} index file(s) would be changed.", file=sys.stderr)
            return 1
        print("OK — no index would change.")
        return 0
    print(f"{changed_total} index file(s) updated." if changed_total else "No index changed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
