agent:
  algorithm: "PPO"
  lr_actor: 0.0003
  lr_critic: 0.001
  gamma: 0.99
  K_epochs: 4
  eps_clip: 0.2
  update_timestep: 1000 # Update every 1000 steps
  frame_stack: 4
  actor_fc_layers: [64, 64]
  critic_fc_layers: [64, 64]
  entropy_coef: 0.01
  gae_lambda: 0.95
  vf_coef: 0.5
  activation: "tanh"
  return_mode: "MC"
  hidden_size: 64
  num_steps: 1
