agent:
  algorithm: "RecurrentPPO"
  lr_actor: 0.0005
  lr_critic: 0.0001
  gamma: 0.95
  K_epochs: 4
  eps_clip: 0.1
  update_timestep: 2000
  sequence_length: 64
  frame_stack: 1
  fc_layers: [128,128]
  recurrent_layers: [64]
  actor_fc_layers: [128,128]
  critic_fc_layers: [128,128]
  num_steps: 128
  hidden_size: 64
  entropy_coef: 0.01
  gae_lambda: 0.95
  vf_coef: 0.5
