wandb:
  entity: "sungwoolee"
  project: "grid_world_pain"
  group: null
  job_type: "debugging" # Default job type (e.g., training, evaluation, sweep)
  mode: "online" # set to "disabled" to turn off logging globally
