#!/usr/bin/env python3
"""Walk docs/memory/, build insight+session graph, produce GRAPH_REPORT.md and per-insight Backlinks blocks.

Usage:
    python scripts/regen_memory_graph.py                  # default: regenerate everything
    python scripts/regen_memory_graph.py --check          # read-only; exit 1 if any file would change
    python scripts/regen_memory_graph.py --with-turn-counts  # compute JSONL turn counts (slower)
    python scripts/regen_memory_graph.py --root docs/memory  # override default root
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ROOT = ROOT / "docs" / "memory"

# Regex to match insight IDs inside [[...]] tokens.
# Excludes coordinate arrays like [[1,1],[5,5]] because those contain commas/digits not matching the slug pattern.
ID_PATTERN = re.compile(r"\[\[(\d{8}_\d{4}_[a-z0-9_]+)(?:\|[^\]]+)?\]\]")

# UUID pattern for session IDs (8-4-4-4-12 hex).
UUID_PATTERN = re.compile(
    r"([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})", re.IGNORECASE
)

# pre-sync placeholder node ID
PRE_SYNC_NODE = "pre-sync"

BACKLINKS_START = "<!-- BACKLINKS — auto-generated by scripts/regen_memory_graph.py; do not edit -->"
BACKLINKS_END = "<!-- END BACKLINKS -->"

# ─── Helpers ────────────────────────────────────────────────────────────────


def _human_size(n_bytes: int) -> str:
    """Format bytes as human-readable string."""
    for unit in ("B", "KB", "MB", "GB"):
        if n_bytes < 1024:
            return f"{n_bytes:.1f} {unit}"
        n_bytes //= 1024
    return f"{n_bytes:.1f} TB"


def _parse_frontmatter(text: str) -> dict[str, str] | None:
    """Return frontmatter key→value dict (raw strings) or None if not found."""
    if not text.startswith("---\n"):
        return None
    fm_end = text.find("\n---\n", 4)
    if fm_end == -1:
        return None
    fm_block = text[4:fm_end]
    result: dict[str, str] = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            result[key.strip()] = val.strip()
    return result


def _extract_uuid_from_raw_source(raw_source: str) -> str | None:
    """Extract a session UUID from a raw_source field value.

    Returns the UUID string, or None if not found (e.g. _archive/... paths or 'none').
    """
    m = UUID_PATTERN.search(raw_source)
    if m:
        return m.group(1).lower()
    return None


def _jsonl_path_from_uuid(uuid: str) -> Path:
    """Construct the repo-relative JSONL path for a session UUID."""
    return (
        ROOT
        / "claude_data"
        / ".claude"
        / "projects"
        / "-media-nas01-projects-Interoceptive-AI-grid-world-pain"
        / f"{uuid}.jsonl"
    )


# ─── Graph building ──────────────────────────────────────────────────────────


class InsightNode:
    __slots__ = (
        "id", "folder", "tags", "date", "summary", "status",
        "raw_source", "path", "outbound", "inbound",
    )

    def __init__(
        self,
        id: str,
        folder: str,
        tags: list[str],
        date: str,
        summary: str,
        status: str,
        raw_source: str,
        path: Path,
    ) -> None:
        self.id = id
        self.folder = folder
        self.tags = tags
        self.date = date
        self.summary = summary
        self.status = status
        self.raw_source = raw_source
        self.path = path
        self.outbound: list[str] = []  # IDs this insight links to (body [[id]] tokens)
        self.inbound: list[str] = []   # IDs that link to this insight (filled in second pass)


class SessionNode:
    __slots__ = (
        "uuid", "jsonl_path", "jsonl_byte_size", "derived_insights",
        "topic_folders_touched", "first_insight_date", "last_insight_date",
    )

    def __init__(self, uuid: str) -> None:
        self.uuid = uuid
        self.jsonl_path: Path | None = None
        self.jsonl_byte_size: int | None = None
        self.derived_insights: list[str] = []
        self.topic_folders_touched: list[str] = []
        self.first_insight_date: str = ""
        self.last_insight_date: str = ""


def _parse_tags(raw: str) -> list[str]:
    """Parse tags: [a, b, c] or tags: [a] into a list of strings."""
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1]
        return [t.strip().strip('"').strip("'") for t in inner.split(",") if t.strip()]
    if raw:
        return [raw.strip().strip('"').strip("'")]
    return []


def collect_insights(memory_root: Path) -> list[Path]:
    """Return all insight .md files (excluding index files and archive)."""
    memories = memory_root / "memories"
    if not memories.is_dir():
        return []
    paths = []
    for p in sorted(memories.rglob("*.md")):
        # skip index files
        if p.name in ("_topic_index.md", "_global_tags.md"):
            continue
        # skip _archive and .trash directories anywhere in path
        parts = set(p.parts)
        if "_archive" in parts or ".trash" in parts:
            continue
        paths.append(p)
    return paths


def build_graph(
    insight_paths: list[Path],
) -> tuple[dict[str, InsightNode], dict[str, SessionNode]]:
    """Build insight and session nodes.  Returns (insights, sessions)."""
    insights: dict[str, InsightNode] = {}
    sessions: dict[str, SessionNode] = {}

    # --- Phase 1: parse every insight file --------------------------------
    for path in insight_paths:
        text = path.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        if fm is None:
            continue
        insight_id = fm.get("id", "").strip()
        if not insight_id:
            continue

        folder = fm.get("folder", path.parent.name).strip()
        tags = _parse_tags(fm.get("tags", ""))
        date = fm.get("date", "").strip()
        summary = fm.get("summary", "").strip().strip('"')
        status = fm.get("status", "active").strip()
        raw_source = fm.get("raw_source", "").strip()

        node = InsightNode(
            id=insight_id,
            folder=folder,
            tags=tags,
            date=date,
            summary=summary,
            status=status,
            raw_source=raw_source,
            path=path,
        )
        insights[insight_id] = node

        # extract body [[id]] tokens for outbound edges
        # body starts after the closing frontmatter fence
        fm_end = text.find("\n---\n", 4)
        body = text[fm_end + 5:] if fm_end != -1 else ""
        # Strip any existing BACKLINKS block before scanning for [[id]] tokens —
        # otherwise on a second run the backlinks block itself would contribute
        # spurious outbound edges and break idempotency.
        bl_start = body.find(BACKLINKS_START)
        body_scan = body[:bl_start] if bl_start != -1 else body
        outbound_ids = list(dict.fromkeys(ID_PATTERN.findall(body_scan)))
        # Self-link defensive filter
        node.outbound = [oid for oid in outbound_ids if oid != insight_id]

        # --- Session node linkage ---
        uuid = _extract_uuid_from_raw_source(raw_source)
        if uuid:
            if uuid not in sessions:
                sessions[uuid] = SessionNode(uuid)
                # resolve JSONL path
                jpath = _jsonl_path_from_uuid(uuid)
                sessions[uuid].jsonl_path = jpath
                if jpath.exists():
                    sessions[uuid].jsonl_byte_size = jpath.stat().st_size
            sessions[uuid].derived_insights.append(insight_id)
            # track folders touched
            if folder not in sessions[uuid].topic_folders_touched:
                sessions[uuid].topic_folders_touched.append(folder)
            # track date range
            if date:
                if not sessions[uuid].first_insight_date or date < sessions[uuid].first_insight_date:
                    sessions[uuid].first_insight_date = date
                if not sessions[uuid].last_insight_date or date > sessions[uuid].last_insight_date:
                    sessions[uuid].last_insight_date = date
        else:
            # non-UUID raw_source → pre-sync placeholder
            if PRE_SYNC_NODE not in sessions:
                sessions[PRE_SYNC_NODE] = SessionNode(PRE_SYNC_NODE)
            sessions[PRE_SYNC_NODE].derived_insights.append(insight_id)
            if folder not in sessions[PRE_SYNC_NODE].topic_folders_touched:
                sessions[PRE_SYNC_NODE].topic_folders_touched.append(folder)
            if date:
                if not sessions[PRE_SYNC_NODE].first_insight_date or date < sessions[PRE_SYNC_NODE].first_insight_date:
                    sessions[PRE_SYNC_NODE].first_insight_date = date
                if not sessions[PRE_SYNC_NODE].last_insight_date or date > sessions[PRE_SYNC_NODE].last_insight_date:
                    sessions[PRE_SYNC_NODE].last_insight_date = date

    # --- Phase 2: populate inbound edges from outbound sets ---------------
    for src_id, src_node in insights.items():
        for dst_id in src_node.outbound:
            if dst_id in insights:
                insights[dst_id].inbound.append(src_id)
            # broken refs are collected in the report section

    # Sort inbound for determinism
    for node in insights.values():
        node.inbound.sort()

    # Sort session derived lists for determinism
    for s in sessions.values():
        s.derived_insights.sort()

    return insights, sessions


def count_turns(jsonl_path: Path) -> int | None:
    """Count lines in a JSONL file (each line = one turn). Returns None on error."""
    try:
        count = 0
        with jsonl_path.open("rb") as f:
            for _ in f:
                count += 1
        return count
    except Exception:
        return None


# ─── GRAPH_REPORT.md generation ─────────────────────────────────────────────


def _render_report(
    insights: dict[str, InsightNode],
    sessions: dict[str, SessionNode],
    with_turn_counts: bool,
) -> str:
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M")

    # Count total edges (outbound; unique source→dest pairs)
    total_edges = sum(len(n.outbound) for n in insights.values())
    n_sessions = len([s for s in sessions if s != PRE_SYNC_NODE]) + (1 if PRE_SYNC_NODE in sessions else 0)

    lines: list[str] = []
    lines.append("# GRAPH_REPORT.md — `docs/memory/` link-graph overview")
    lines.append("")
    lines.append("> Auto-generated by `scripts/regen_memory_graph.py`. Do not hand-edit.")
    lines.append(f"> Last generated: {now}")
    lines.append(f"> Insights: {len(insights)} | Sessions: {n_sessions} | Edges: {total_edges}")
    lines.append("")

    # ── Section 1: God nodes ──────────────────────────────────────────────
    lines.append("## God nodes (top-10 by inbound link count)")
    lines.append("| Rank | Insight | Folder | Inbound | Summary |")
    lines.append("|---|---|---|:---:|---|")
    by_inbound = sorted(insights.values(), key=lambda n: (-len(n.inbound), n.id))
    # Show top 10 with at least 1 inbound
    shown = 0
    for rank, node in enumerate(by_inbound, 1):
        if shown >= 10:
            break
        if len(node.inbound) == 0 and shown == 0:
            lines.append("| — | _No insight has inbound links yet._ | | | |")
            break
        if len(node.inbound) == 0:
            break
        summary_short = node.summary[:80] + "…" if len(node.summary) > 80 else node.summary
        lines.append(
            f"| {rank} | [[{node.id}]] | {node.folder} | {len(node.inbound)} | {summary_short} |"
        )
        shown += 1
    lines.append("")

    # ── Section 2: Orphans ───────────────────────────────────────────────
    lines.append("## Orphans (no inbound and no outbound links)")
    orphans = [
        n for n in sorted(insights.values(), key=lambda n: n.date)
        if len(n.inbound) == 0 and len(n.outbound) == 0
    ]
    if orphans:
        for o in orphans:
            lines.append(f"- [[{o.id}]] ({o.folder}, {o.date}) — {o.summary[:80]}")
    else:
        lines.append("None — every insight is connected to at least one other.")
    lines.append("")

    # ── Section 3: Broken refs ───────────────────────────────────────────
    lines.append("## Broken refs (`[[id]]` tokens that don't resolve to a real file)")
    broken: list[tuple[str, str]] = []
    for src_id, src_node in sorted(insights.items()):
        for dst_id in src_node.outbound:
            if dst_id not in insights:
                broken.append((src_id, dst_id))
    if broken:
        for src_id, dst_id in broken:
            src_folder = insights[src_id].folder
            lines.append(f"- In [[{src_id}]] ({src_folder}): `[[{dst_id}]]`")
    else:
        lines.append("None — all wikilinks resolve.")
    lines.append("")

    # ── Section 4: Tag clusters ──────────────────────────────────────────
    lines.append("## Tag clusters (pairs of tags co-occurring ≥ 3 times)")
    lines.append("| Tag pair | Co-occurrences | Example insights |")
    lines.append("|---|:---:|---|")

    # Count co-occurrences
    pair_counts: dict[tuple[str, str], list[str]] = defaultdict(list)
    for node in insights.values():
        tags = sorted(set(node.tags))
        for i in range(len(tags)):
            for j in range(i + 1, len(tags)):
                pair = (tags[i], tags[j])
                pair_counts[pair].append(node.id)

    clusters = [
        (pair, ids) for pair, ids in pair_counts.items() if len(ids) >= 3
    ]
    clusters.sort(key=lambda x: -len(x[1]))

    if clusters:
        for pair, ids in clusters:
            # show up to 3 example IDs
            examples = ", ".join(f"[[{i}]]" for i in ids[:3])
            lines.append(f"| `{pair[0]}` + `{pair[1]}` | {len(ids)} | {examples} |")
    else:
        lines.append("| — | — | _No tag pairs co-occur ≥ 3 times yet._ |")
    lines.append("")

    # ── Section 5: Surprising connections ────────────────────────────────
    lines.append("## Surprising connections (cross-folder edges)")
    cross_folder: list[tuple[str, str, str, str, str]] = []
    for src_id, src_node in insights.items():
        for dst_id in src_node.outbound:
            if dst_id in insights:
                dst_node = insights[dst_id]
                if src_node.folder != dst_node.folder:
                    cross_folder.append(
                        (src_node.folder, src_node.date, src_id, dst_id, dst_node.folder)
                    )

    if cross_folder:
        # Sort by source folder then by date desc
        cross_folder.sort(key=lambda t: (t[0], t[1] if t[1] else ""), reverse=False)
        cross_folder.sort(key=lambda t: t[0])
        for src_folder, _date, src_id, dst_id, dst_folder in cross_folder:
            lines.append(
                f"- [[{src_id}]] (folder={src_folder}) → [[{dst_id}]] (folder={dst_folder})"
            )
    else:
        lines.append("_No cross-folder edges yet._")
    lines.append("")

    # ── Section 6: Conversation provenance ───────────────────────────────
    lines.append("## Conversation provenance")
    lines.append("")

    # Sort sessions in reverse-chronological order of first_insight_date;
    # pre-sync goes last.
    real_sessions = [
        s for uuid, s in sessions.items() if uuid != PRE_SYNC_NODE
    ]
    real_sessions.sort(key=lambda s: s.first_insight_date or "", reverse=True)

    for s in real_sessions:
        # Size
        if s.jsonl_byte_size is not None:
            size_str = _human_size(s.jsonl_byte_size)
        else:
            size_str = "not synced locally"

        # Turn count
        if with_turn_counts and s.jsonl_path is not None and s.jsonl_path.exists():
            turns = count_turns(s.jsonl_path)
            turn_str = str(turns) if turns is not None else "unknown"
        else:
            turn_str = "unknown"

        lines.append(f"### Session {s.uuid} ({size_str}, {turn_str} turns)")
        date_range = f"{s.first_insight_date} → {s.last_insight_date}" if s.first_insight_date else "unknown"
        lines.append(f"- Date range: {date_range}")
        folders_str = ", ".join(sorted(s.topic_folders_touched))
        lines.append(f"- Topic folders: {folders_str}")
        insights_str = ", ".join(f"[[{i}]]" for i in s.derived_insights)
        lines.append(f"- Derived insights: {insights_str}")

        # Restore commands
        if s.jsonl_path is not None:
            jsonl_rel = s.jsonl_path.relative_to(ROOT) if s.jsonl_path.is_absolute() else s.jsonl_path
            uuid_prefix = s.uuid[:8]
            restore_line = (
                f"- Restore: `claude --resume {s.uuid}` | "
                f"`python scripts/claude_jsonl_to_md.py {jsonl_rel} /tmp/{uuid_prefix}.md`"
            )
        else:
            restore_line = f"- Restore: `claude --resume {s.uuid}`"
        lines.append(restore_line)
        lines.append("")

    # Pre-sync placeholder
    if PRE_SYNC_NODE in sessions:
        ps = sessions[PRE_SYNC_NODE]
        n_ps = len(ps.derived_insights)
        lines.append(f"### Session pre-sync ({n_ps} insights, no JSONL)")
        lines.append("- Genesis insights captured before the sync workflow.")
        insights_str = ", ".join(f"[[{i}]]" for i in ps.derived_insights)
        lines.append(f"- Insights: {insights_str}")
        lines.append("")

    return "\n".join(lines) + "\n"


# ─── Per-insight Backlinks blocks ────────────────────────────────────────────


def _backlinks_block(inbound: list[str], insights: dict[str, InsightNode]) -> str:
    """Render the BACKLINKS block content (without outer markers)."""
    lines = ["## Backlinks"]
    if inbound:
        for iid in inbound:
            if iid in insights:
                n = insights[iid]
                lines.append(f"- [[{iid}]] ({n.folder}, {n.date}) — {n.summary[:80]}")
            else:
                lines.append(f"- [[{iid}]]")
    else:
        lines.append("- _no inbound links yet_")
    return "\n".join(lines)


def _inject_backlinks(
    path: Path,
    insight_id: str,
    inbound: list[str],
    insights: dict[str, InsightNode],
    dry_run: bool = False,
) -> bool:
    """Inject or replace the BACKLINKS block in a single insight file.

    Returns True if the file was changed.
    """
    text = path.read_text(encoding="utf-8")

    # Defensive: filter self-links
    safe_inbound = [iid for iid in inbound if iid != insight_id]
    # Sort for determinism
    safe_inbound = sorted(safe_inbound)

    new_block_body = _backlinks_block(safe_inbound, insights)
    new_block = f"{BACKLINKS_START}\n{new_block_body}\n{BACKLINKS_END}"

    start_idx = text.find(BACKLINKS_START)
    end_idx = text.find(BACKLINKS_END)

    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        # Replace existing block (content between markers inclusive)
        existing_block = text[start_idx: end_idx + len(BACKLINKS_END)]
        if existing_block == new_block:
            return False  # already up-to-date
        new_text = text[:start_idx] + new_block + text[end_idx + len(BACKLINKS_END):]
    else:
        # No markers found — append
        stripped = text.rstrip("\n")
        new_text = stripped + "\n\n" + new_block + "\n"

    if new_text == text:
        return False

    if not dry_run:
        path.write_text(new_text, encoding="utf-8")
        print(f"backlinks: {path.relative_to(ROOT)}")
    return True


# ─── Main ────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build memory link-graph; produce GRAPH_REPORT.md and per-insight Backlinks blocks."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Read-only; exit 0 if no files would change, 1 otherwise.",
    )
    parser.add_argument(
        "--with-turn-counts",
        action="store_true",
        help="Compute JSONL turn counts (slower — reads every line of each JSONL).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help="Root of the memory layer (default: docs/memory).",
    )
    args = parser.parse_args()

    insight_paths = collect_insights(args.root)
    if not insight_paths:
        print(f"No insight files found under {args.root}", file=sys.stderr)
        return 1

    insights, sessions = build_graph(insight_paths)

    changed_files = 0

    # ── Write GRAPH_REPORT.md ────────────────────────────────────────────
    report_path = args.root / "GRAPH_REPORT.md"
    report_content = _render_report(insights, sessions, args.with_turn_counts)

    existing_report = report_path.read_text(encoding="utf-8") if report_path.exists() else None

    # For idempotency checking, ignore the "Last generated:" timestamp line.
    # Substantive content (graph structure) must match; the wall-clock stamp is irrelevant.
    _TIMESTAMP_RE = re.compile(r"^> Last generated: .*$", re.MULTILINE)

    def _strip_timestamp(s: str) -> str:
        return _TIMESTAMP_RE.sub("> Last generated: <TIMESTAMP>", s)

    # Substantive change = content differs beyond the timestamp
    substantive_change = (
        existing_report is None
        or _strip_timestamp(existing_report) != _strip_timestamp(report_content)
    )
    # Any change (including timestamp refresh) for non-check runs
    any_change = existing_report != report_content

    if args.check:
        if substantive_change:
            changed_files += 1
            print(f"would change: GRAPH_REPORT.md")
        # else: timestamp-only difference — not a substantive change; don't count
    else:
        if any_change:
            report_path.write_text(report_content, encoding="utf-8")
            if substantive_change:
                print(f"wrote: {report_path.relative_to(ROOT)}")
            else:
                print(f"refreshed timestamp: {report_path.relative_to(ROOT)}")
        else:
            print("GRAPH_REPORT.md already up-to-date.")

    # ── Inject Backlinks blocks ──────────────────────────────────────────
    for node in insights.values():
        changed = _inject_backlinks(
            path=node.path,
            insight_id=node.id,
            inbound=node.inbound,
            insights=insights,
            dry_run=args.check,
        )
        if changed:
            changed_files += 1
            if args.check:
                print(f"would change: {node.path.relative_to(ROOT)}")

    if args.check:
        if changed_files:
            print(f"{changed_files} file(s) would be changed.", file=sys.stderr)
            return 1
        print("OK — no files would change.")
        return 0

    if changed_files == 0:
        print("No files changed.")
    else:
        print(f"{changed_files} file(s) updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
