#!/usr/bin/env python3
"""Regenerate docs/develop/INDEX.md from frontmatter.

Walks docs/develop/{active,archive}/, parses YAML frontmatter, and writes a
deterministic INDEX.md grouped by topic and lifecycle status. Validates
required fields and supersedes/superseded_by chains; exits nonzero on any
validation error so the script can serve as a pre-commit hook.

Usage:
    python scripts/regen_dev_index.py
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEVELOP = ROOT / "docs" / "develop"
INDEX = DEVELOP / "INDEX.md"

REQUIRED_FIELDS = {"title", "topic", "status", "created", "last_updated"}
VALID_STATUS = {"active", "superseded", "archive"}
VALID_TOPICS = {
    "filim",
    "precision",
    "noise",
    "hypervigilance",
    "neuromodulation",
    "diagnosis",
    "dreamer",
    "continual_learning",
    "behavior",
    "sensors",
    "refactors",
    "issues",
    "meta",
}


def parse_frontmatter(path: Path) -> dict | None:
    """Read a markdown file's YAML frontmatter; return None if absent."""
    text = path.read_text()
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    try:
        return yaml.safe_load(text[4:end]) or {}
    except yaml.YAMLError as exc:
        print(f"YAML parse error in {path}: {exc}", file=sys.stderr)
        return {}


def collect_docs() -> list[tuple[Path, dict]]:
    docs: list[tuple[Path, dict]] = []
    for sub in ("active", "archive"):
        base = DEVELOP / sub
        if not base.exists():
            continue
        for md in sorted(base.rglob("*.md")):
            fm = parse_frontmatter(md)
            if fm is None:
                # No frontmatter — skip (e.g., a transitional plan doc still
                # using the issue_plan template format).
                continue
            docs.append((md, fm))
    return docs


def validate(docs: list[tuple[Path, dict]]) -> list[str]:
    errors: list[str] = []
    by_name = {p.name: (p, fm) for p, fm in docs}
    for path, fm in docs:
        rel = path.relative_to(DEVELOP)
        missing = REQUIRED_FIELDS - set(fm)
        if missing:
            errors.append(f"{rel}: missing required fields: {sorted(missing)}")
        if fm.get("status") not in VALID_STATUS:
            errors.append(f"{rel}: invalid status: {fm.get('status')!r}")
        if fm.get("topic") not in VALID_TOPICS:
            errors.append(f"{rel}: invalid topic: {fm.get('topic')!r}")
        for chain_field in ("supersedes", "superseded_by"):
            target = fm.get(chain_field)
            if target and target not in by_name:
                errors.append(
                    f"{rel}: {chain_field} -> {target!r} (target not found in develop/)"
                )
    return errors


def render_index(docs: list[tuple[Path, dict]]) -> str:
    active = [(p, fm) for p, fm in docs if fm.get("status") == "active"]
    archived = [
        (p, fm) for p, fm in docs if fm.get("status") in ("superseded", "archive")
    ]

    by_topic: dict[str, list[tuple[Path, dict]]] = {}
    for p, fm in active:
        by_topic.setdefault(fm["topic"], []).append((p, fm))

    lines = [
        "# Develop Docs Index",
        "",
        f"> AUTO-GENERATED by `scripts/regen_dev_index.py` on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.",
        "> Do not edit by hand. Re-run the script after changing any frontmatter.",
        "",
        f"**Active**: {len(active)} docs · **Archive**: {len(archived)} docs",
        "",
        "## Active",
        "",
    ]

    for topic in sorted(by_topic):
        lines.append(f"### {topic}")
        lines.append("")
        for p, fm in sorted(
            by_topic[topic], key=lambda x: x[1].get("last_updated", ""), reverse=True
        ):
            rel = p.relative_to(DEVELOP)
            phase = f" — phase {fm['phase']}" if fm.get("phase") else ""
            lines.append(
                f"- [{fm['title']}]({rel}) — updated {fm['last_updated']}{phase}"
            )
        lines.append("")

    lines.append("## Archive (superseded or one-off)")
    lines.append("")

    archive_by_topic: dict[str, list[tuple[Path, dict]]] = {}
    for p, fm in archived:
        archive_by_topic.setdefault(fm["topic"], []).append((p, fm))

    for topic in sorted(archive_by_topic):
        lines.append(f"### {topic}")
        lines.append("")
        for p, fm in sorted(
            archive_by_topic[topic],
            key=lambda x: x[1].get("last_updated", ""),
            reverse=True,
        ):
            rel = p.relative_to(DEVELOP)
            chain = ""
            if fm.get("superseded_by"):
                chain = f" → superseded by `{fm['superseded_by']}`"
            lines.append(f"- [{fm['title']}]({rel}){chain}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    if not DEVELOP.exists():
        print(f"docs/develop/ not found at {DEVELOP}", file=sys.stderr)
        return 1

    docs = collect_docs()
    errors = validate(docs)
    if errors:
        print("Validation errors:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    INDEX.write_text(render_index(docs))
    print(f"Wrote {INDEX.relative_to(ROOT)} ({len(docs)} docs indexed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
