# Level 04: +Nociception
# Focus: Role of pain in state detection.
# Dynamics: Dynamic switching at fixed location.
sensory:
  using_sensory: true
  nociception_enabled: true
  olfactory_enabled: false
  proprioception_enabled: false
  collision_sensor_enabled: false
  location_sensor: false

environment:
  max_steps: 200
  prob_switch_to_danger: 0.1
  prob_switch_to_food: 0.5
  relocate_resource: false
  eat_action_enabled: false
  rest_action_enabled: true

body:
  with_satiation: false
  with_health: true
  health_recovery: 2.0
  use_homeostatic_reward: false
