# Level 05: +Olfactory / Forage
# Focus: Search/Foraging under hunger.
# Milestone: Relocation + Satiation + Olfaction + Eat Action enabled.
sensory:
  using_sensory: true
  nociception_enabled: true
  olfactory_enabled: true
  proprioception_enabled: false
  collision_sensor_enabled: false
  location_sensor: false

environment:
  max_steps: 500
  relocate_resource: true
  prob_switch_to_danger: 0.1
  prob_switch_to_food: 0.5
  eat_action_enabled: true
  rest_action_enabled: true

body:
  with_satiation: true
  with_health: true
  random_start_satiation: true
  use_homeostatic_reward: false
